export type ChristmasWallpaper = {
  id: string
  src: string
  alt: string
  themes: string[]
}

export const CHRISTMAS_WALLPAPERS: ChristmasWallpaper[] = [
  {
    id: "cute-wallpaper-for-christmas-wallpapers-cozy-christmas-01-png",
    src: "/wallpapers/Cozy Christmas wallpapers/:wallpapers:Cozy Christmas 01.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-wallpapers-cozy-christmas-02-png",
    src: "/wallpapers/Cozy Christmas wallpapers/:wallpapers:Cozy Christmas 02.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-1-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 1.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-10-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 10.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-11-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 11.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-14-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 14.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-17-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 17.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-2-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 2.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-20-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 20.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-21-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 21.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-23-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 23.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-29-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 29.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-30-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 30.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-32-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 32.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-5-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 5.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-6-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 6.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-1-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (1).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-13-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (13).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-20-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (20).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-21-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (21).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-22-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (22).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-23-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (23).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-24-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (24).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-3-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (3).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-7-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (7).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-8-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (8).png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "winter-cabin-at-night-wallpapers-cyber-steam-punk-01-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/:wallpapers:Cyber Steam-Punk 01.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-new-24-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/new 24.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-new-25-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/new 25.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-new-26-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/new 26.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-new-28-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/new 28.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-11-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (11).png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-12-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (12).png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-14-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (14).png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-34-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (34).png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-35-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (35).png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "christmas-tree-lights-wallpapers-christmas-tree-01-png",
    src: "/wallpapers/Christmas Tree wallpapers/:wallpapers:Christmas Tree 01.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-20251206-0937-cosmic-christmas-tree-simple-compose-01kbrmww7xekcbv4ez6224mxe0-png",
    src: "/wallpapers/Christmas Tree wallpapers/20251206_0937_Cosmic Christmas Tree_simple_compose_01kbrmww7xekcbv4ez6224mxe0.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-15-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 15.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-22-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 22.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-27-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 27.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-3-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 3.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-4-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 4.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-40-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 40.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-out-0-36-png",
    src: "/wallpapers/Christmas Tree wallpapers/out-0 (36).png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-out-0-37-png",
    src: "/wallpapers/Christmas Tree wallpapers/out-0 (37).png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-out-0-4-png",
    src: "/wallpapers/Christmas Tree wallpapers/out-0 (4).png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-out-0-5-png",
    src: "/wallpapers/Christmas Tree wallpapers/out-0 (5).png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "ice-castle-queen-20251205-2039-epic-christmas-warrior-simple-compose-01kbq88ht5e03skn5sj4c20zzv-png",
    src: "/wallpapers/Horror Christmas wallpapers/20251205_2039_Epic Christmas Warrior_simple_compose_01kbq88ht5e03skn5sj4c20zzv.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-20251206-0015-manga-horror-showdown-simple-compose-01kbqmmnkhfdcrst3rpbr8w1q9-png",
    src: "/wallpapers/Horror Christmas wallpapers/20251206_0015_Manga Horror Showdown_simple_compose_01kbqmmnkhfdcrst3rpbr8w1q9.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-35-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 35.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-37-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 37.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-38-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 38.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-39-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 39.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-43-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 43.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-46-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 46.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-47-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 47.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-48-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 48.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-49-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 49.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-51-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 51.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-52-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 52.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-53-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 53.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-54-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 54.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-55-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 55.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-56-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 56.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-57-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 57.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-58-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 58.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-60-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 60.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-61-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 61.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-62-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 62.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "cosmic-space-christmas-wallpapers-cosmic-christmas-01-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/:wallpapers:Cosmic Christmas 01.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-20251205-1521-futuristic-santa-sleigh-simple-compose-01kbpp2hk9em7tgat45jsh95r6-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/20251205_1521_Futuristic Santa Sleigh_simple_compose_01kbpp2hk9em7tgat45jsh95r6.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-20251205-1525-glowing-orbs-in-snow-simple-compose-01kbppa7t0ezabafdg98zvc6hv-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/20251205_1525_Glowing Orbs in Snow_simple_compose_01kbppa7t0ezabafdg98zvc6hv.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-20251205-1528-candy-cane-ringworld-simple-compose-01kbpph0r8fkbrn2p6x960m1k8-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/20251205_1528_Candy Cane Ringworld_simple_compose_01kbpph0r8fkbrn2p6x960m1k8.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-20251205-1540-celestial-angel-with-lantern-simple-compose-01kbpq5sngew1b7gdj74apayge-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/20251205_1540_Celestial Angel with Lantern_simple_compose_01kbpq5sngew1b7gdj74apayge.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-new-19-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/new 19.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-out-0-40-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/out-0 (40).png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cute-christmas-robots-wallpapers-cute-robots-01-png",
    src: "/wallpapers/Cute Robots wallpapers/:wallpapers:Cute Robots 01.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-1545-gingerbread-robot-delight-simple-compose-01kbpqfgcsf4n9npzvmaq635a3-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_1545_Gingerbread Robot Delight_simple_compose_01kbpqfgcsf4n9npzvmaq635a3.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-1559-festive-delivery-robot-simple-compose-01kbpr8gfeeb68v4fpj2mf4wf2-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_1559_Festive Delivery Robot_simple_compose_01kbpr8gfeeb68v4fpj2mf4wf2.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-2007-dreamy-robotic-reindeer-simple-compose-01kbq6evw0f7er927xj14vy8bd-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_2007_Dreamy Robotic Reindeer_simple_compose_01kbq6evw0f7er927xj14vy8bd.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-2016-robots-in-santa-s-workshop-simple-compose-01kbq6ymkjf4etd3edrgr3jkb1-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_2016_Robots in Santa's Workshop_simple_compose_01kbq6ymkjf4etd3edrgr3jkb1.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-2021-futuristic-snowman-delight-simple-compose-01kbq77ah6fqcrd59cdmzg71n1-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_2021_Futuristic Snowman Delight_simple_compose_01kbq77ah6fqcrd59cdmzg71n1.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-new-16-png",
    src: "/wallpapers/Cute Robots wallpapers/new 16.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-new-31-png",
    src: "/wallpapers/Cute Robots wallpapers/new 31.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-out-0-39-png",
    src: "/wallpapers/Cute Robots wallpapers/out-0 (39).png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "pastel-candy-christmas-20251205-2027-cotton-candy-dreamland-simple-compose-01kbq7j43yf8y8a1np9z8ecc49-png",
    src: "/wallpapers/Pastel Candy wallpapers/20251205_2027_Cotton Candy Dreamland_simple_compose_01kbq7j43yf8y8a1np9z8ecc49.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-20251205-2032-pastel-candy-christmas-simple-compose-01kbq7w8gyfxkt23cyy2djb7hv-png",
    src: "/wallpapers/Pastel Candy wallpapers/20251205_2032_Pastel Candy Christmas_simple_compose_01kbq7w8gyfxkt23cyy2djb7hv.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-20251205-2035-lollipop-forest-enchantment-simple-compose-01kbq82esnejfrhph5xpadr1hw-png",
    src: "/wallpapers/Pastel Candy wallpapers/20251205_2035_Lollipop Forest Enchantment_simple_compose_01kbq82esnejfrhph5xpadr1hw.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-20251205-2127-candy-animal-winterland-simple-compose-01kbqb0494fw8btazcg3tk90sv-png",
    src: "/wallpapers/Pastel Candy wallpapers/20251205_2127_Candy Animal Winterland_simple_compose_01kbqb0494fw8btazcg3tk90sv.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-out-0-29-png",
    src: "/wallpapers/Pastel Candy wallpapers/out-0 (29).png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-out-0-30-png",
    src: "/wallpapers/Pastel Candy wallpapers/out-0 (30).png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-out-0-31-png",
    src: "/wallpapers/Pastel Candy wallpapers/out-0 (31).png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "snowy-forest-aesthetic-wallpapers-snow-aesthetic-01-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/:wallpapers:Snow Aesthetic 01.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-wallpapers-snow-aesthetic-02-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/:wallpapers:Snow Aesthetic 02.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-20251205-2053-anime-empress-christmas-elegance-simple-compose-01kbq932cnfpxr8w3na7d510kw-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/20251205_2053_Anime Empress Christmas Elegance_simple_compose_01kbq932cnfpxr8w3na7d510kw.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-12-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 12.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-13-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 13.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-18-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 18.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-33-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 33.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-34-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 34.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-36-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 36.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-41-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 41.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-42-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 42.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-7-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 7.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-8-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 8.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-9-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 9.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-10-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (10).png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-16-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (16).png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-27-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (27).png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-32-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (32).png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-33-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (33).png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-42-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (42).png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-43-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (43).png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-9-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (9).png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  }
]
