export type ChristmasWallpaper = {
  id: string
  src: string
  thumbnailSrc: string
  blurDataURL: string
  downloadName: string
  alt: string
  themes: string[]
}

export const CHRISTMAS_WALLPAPERS: ChristmasWallpaper[] = [
  {
    id: "cute-wallpaper-for-christmas-wallpapers-cozy-christmas-01-png",
    src: "/wallpapers/Cozy Christmas wallpapers/:wallpapers:Cozy Christmas 01.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/wallpapers-cozy-christmas-01.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYBAABXRUJQVlA4IEoBAACQCQCdASoYADAAPu1Ypk2ppKOiMBqtUTAdiWoAnTKEgsyA8RIf761z0mmZ7v+wVtkAHnX6c1TlwSlrD5Ys0da4A0fcE/7MYgr0cCes8feZYGse01gAAP72ikwtX8q/0Iq5k5zT1L83FnafGCrjmirgxMy/WBUjaQZJTYg/pcqlPGW2FqOPsBtWkde1coQz2nzeNtTb3wwkwcFo+JG62k3KdvVe2g1Mk3k0R4PlxfZxC5DVRbTyy9yWwkCmjcHpTxosRa+KRCclTZamkedktVrTkP0+2jswA9JtdsB0aZfbv9sI6Fmn0kVuV+hcg3UIBgdYYWHZ4D8iYQ9mG0nE5OnaWsj5QFJGesMwhu307SL03EW7y0tbexk4QmXG2mKCgRegAfesByRQWzwY3eTJ6T4MUFlV1FMsM8chFBIK9+5KL8y+dYi3QJGsAAA=",
    downloadName: "cute-wallpaper-for-christmas-01.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-wallpapers-cozy-christmas-02-png",
    src: "/wallpapers/Cozy Christmas wallpapers/:wallpapers:Cozy Christmas 02.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/wallpapers-cozy-christmas-02.webp",
    blurDataURL: "data:image/webp;base64,UklGRk4BAABXRUJQVlA4IEIBAAAQCACdASoYADAAPu1kq08ppSOiMBqoATAdiUAXZmSYQBqufmlNe8ous3aLZtkD8/Gg58SXmDcj0/26v4EHJGG2xkUlR2XtwhJAAP7GpQjEdza/ARygoC0cwwjuQbea8F1KjKcw1/RKJGxcuhqm0y602jFELT8DRq2R66MVp5w1kla6r/PW/cjYprgys76zfkxgo7CN81cEYq94CC9VsmPgvXmXLb00V8lWNBScw4JUIiUEJLfUAMFu7dDG35hACmBh7TTKuYR2X2g8ZIhfW+VsZP9LUMhYz/dBsEmz+cqjJZkHAVXGCggeyTgLMEk0R2ZBCnfnibaYVIsOcI7Ic+eEA1qD3zMal/vLwUcnk+Zpx8dNnYEz203FN04zyJ4GHmbFrGQZDAoDi/tWJ029/A4TC0qDDrQAv1YdcyRb8OjHPAAA",
    downloadName: "cute-wallpaper-for-christmas-02.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-20251206-2011-boa-s-christmas-gesture-simple-compose-01kbss257ff12taq5p8tc6n2k1-png",
    src: "/wallpapers/Cozy Christmas wallpapers/20251206_2011_Boa's Christmas Gesture_simple_compose_01kbss257ff12taq5p8tc6n2k1.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/20251206-2011-boa-s-christmas-gesture-simple-compose-01kbss257ff12taq5p8tc6n2k1.webp",
    blurDataURL: "data:image/webp;base64,UklGRoQBAABXRUJQVlA4IHgBAADQBwCdASoYACQAPu1kqU6ppaOiKqwBMB2JagCdMoPPIyKGSLw4+BpWWhQZmdV1l1GeNh4Md9bekoUdpxjq3eazaImapuGf4AD3LBcXDvVndewW77E3V/C2oKo+2VDq0m2lf88eDY56nlsa0VKTgnCJd/NX4AhLLPNuGShVo9OoMBAg4JrLtKOiqe84kIv6IJaW763hB8/DaQh3Bt16qQJh6C8BGN1tuMbmV2qdTMd5qb1Mb2RakOgO5Jfv6eV7dA10Mpk8uxKOkGUHx26RtX3eX2di8aq4Nkuoh8Ali3bCXd1kNJpM2HfjMunSeYvLFnXNqzq6NeBPbu0PXi/7DmrbMeSFpTzFSOLrRq6sCIktbFAEknxX7bMKwfjEbGVrN74bF65jQoKkh8//IpzSWjcYo6yw4FPRLCOpg1tbpBxFEwl4WE6YfjqIuW5sm9CfVf+pd7DrcxvBQlJmtBzVu2mXlkPtQpetDMAjLm122OJqnV/q5bhfs9AA",
    downloadName: "cute-wallpaper-for-christmas-03.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-1-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 1.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-1.webp",
    blurDataURL: "data:image/webp;base64,UklGRsIBAABXRUJQVlA4ILYBAABwCACdASoYADAAPu1oqk6ppiOiMBqoATAdiWIAnTNY+9EOZ4Dns2ae2bjArZ0E9vVJyUYqZeCbEHLuSZiXXhHKAG+/Ax1Ise/FHvAAAOJN+FMkes7/qrnkEs7d8x0bKIwni17Mr+4FLYM+cw5X39LFjHVX5ltRzm6Uz1AeJzfzWGZL9vIJexXAEIlQqSk7Pv6ML13laQJMsU0XCFk70hwDz79AI+MVA67hLyQ0+UKyg8NrpAXG6XtM6U6cgB2RNmq2dVD12UzvVqyYCBhVjBF210HDGcHaL+279M3A6kd+AcfyKxCs45pqzKNHYYBguDp048Frg9SWVkhPZns13rQ6yzJcD1UW7IGBjQs7+ZTEDnMtleOgF636U9nHH+Wt5AYxj5r+HsVal6opKW8/LHNHHEwzksPCWqr9A2zj8KslmkfDNbPwmoiF3Bh2tSTVxwcc5WXA+h5gTj+Ux43w0zzNABN0OOG0wnTr5865K+yJ2ujtQmTy+DNMG0Mzn4llDeyuNrCymCTKC1pTebKXNVbmGXFWZJvHdeoOgqLOZP5U9ZDpjvlLYqgoX0e+kWY4KbCB3wrlgAA=",
    downloadName: "cute-wallpaper-for-christmas-04.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-10-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 10.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-10.webp",
    blurDataURL: "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoRwAdFguqCZ5Geb8iC2oAD+qhRIJx3nTKtfqxeNytNAo670aWssHmJInSFGvrkocgaX/DcH/l0N3Kir+EjrrPYJYhaf6TtqSbvBaqqj+a7eRrPot+/W2jfNiqaO2nkcehHb6hT36tRU1BKcmwfnpwQOBiCUvXkNZl3cTrvby5be9p6VzJAc9yDgAAA=",
    downloadName: "cute-wallpaper-for-christmas-05.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-11-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 11.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-11.webp",
    blurDataURL: "data:image/webp;base64,UklGRngBAABXRUJQVlA4IGwBAACQCACdASoYADAAPu1mqlGppSOiqrgKATAdiWYAnTMRs/An4wK22WBpd2iimg4Rm+iWw6cHRERmK7mqay2momdYnnhiis1tQrlxGapiQAD+yzwI76JCQen88X0j+sO+e81bhz2XBu6Sq3nmoMo8lBLUHGPg6HdZqjS6X2u6MwD1aQjOTwNX5LBW3I1o6f2nGVacIPVzk4zoW6e3/q9EfDQdqbBReojSGh0rcNSZ3p5XyXaAuxSQNxMOr63PPsaKbhGjwCsI6RBn5SQYcy+UevTfJ+dlgbkXPBeFlsi44KQ+AGtK5Qg6DwCcU3Nke4xaPjyJvJzY3O/r5uQmTv88gJZbeCMjX67t9sfR5RR9/uov8bT5Q5FhV4CDxFgqOZ/af6eutyqwp3LMIQPjoVPE/mOlJrRpZ5OgZJQdL/F3WMfYXtF6nODqhKH97ja4h0347CcKME9etFXOeaNmfYdQl7de9roapNWQTY6ryAAA",
    downloadName: "cute-wallpaper-for-christmas-06.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-14-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 14.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-14.webp",
    blurDataURL: "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBQCdASoYACQAPu1cqE2ppKOiNVgIATAdiUAVJOhYRvMRQotsKfvnwhMOMtPpWsqgAP7tNjLpDSUGDTgLGSCQPpvRBDoJKTrtS6oMi0D5jK8VGn9OpYY1QMMKhWv5Lm7OIkMFdHn3qPLbUF1vGTAiQehs1ls40R2QEN1xB5fJAAAA",
    downloadName: "cute-wallpaper-for-christmas-07.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-17-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 17.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-17.webp",
    blurDataURL: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoYACQAPu1orlAppaQipWzJMB2JQBb3Ac7Fudkvw98ZgNGBCKoAAP7vowbiATXYuEKQBiX2tI1SITdhbpcP3ygHn+yzVi0StMVzsIMdDE0Yz6DS0pSMMboxVEV+kjjZhu2Jr1RqFxMFdU02OKwO13xa9NRE1TQAAAA=",
    downloadName: "cute-wallpaper-for-christmas-08.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-2-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 2.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-2.webp",
    blurDataURL: "data:image/webp;base64,UklGRhoBAABXRUJQVlA4IA4BAADQBgCdASoYADAAPulgqE2pJaQiKq35IB0JZgDB2iJVAkO/LWT7XBuMpklvBdZ5lVc6rVXI1rJB2YUIVmpSR4AA/u+7p9Bn7uxaWG53R5SpHQPomgjUiXPH9tiV6Yo+Ec4UB4Ebp2Z5UoH8ww8ohuori7ropJldQUZRvXRLt8QRk8O5pKiMsBJxc3tBhN4eYlzDh6pWQY6VNC+DWR+mx9NILV8dbiDOwm54LV27zI0ylrzipwvbUxTbliVPcY2IU0o8eIcyMItC74s3btvlWDx6kG83X83b0ZWhGnvR3591QcXP9Bswo/0L58dfY3B9U0W/Txo+Bx3u3pJaLI/uZyjw5Rl4htHJhKQAVlQAAAA=",
    downloadName: "cute-wallpaper-for-christmas-09.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-20-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 20.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-20.webp",
    blurDataURL: "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAACQBQCdASoYACQAPu1qrFAppiQisBVYATAdiUAYOgEANhMMEK8TVPvWX//bOfrk7lIENxFVQAD+055xUAX695WzAmdh9TAmTze2iNB64ubkTlOx775JvZIojp5m9OSOVyTF0lVh0rDzE3vSqKAl/m07/+ZVRofi5FxW2W1so+9376gpouTrKiLNkveLfsk9p8uNgqc5MW2HhhjlJt+70xNCw5m2ReNKXwhu++8OMt7d8lELznyjcEW+uAA=",
    downloadName: "cute-wallpaper-for-christmas-10.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-21-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 21.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-21.webp",
    blurDataURL: "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAQBgCdASoYACQAPu1mqE6ppaOiKqwBMB2JaACCiT7gOklC2Qv0NJgKAaC5TevQzZOaIgcsavoSfqAA/gIrIi21Uvt80DlbVAb3/0H286VAlbJwtKU6qoL+jjJY+I+1zLK5Tc8gB2yIVt4wQ0JzxnbvHOc2cdKBUgs+66oQ0HR8nZh2ePBXoLCgLgD0Kp27vONgRcHSPwA7FTGZNV2FwLS+J+0VJL0gM4CGqoTVkzMeQHdYAwAAAA==",
    downloadName: "cute-wallpaper-for-christmas-11.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-23-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 23.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-23.webp",
    blurDataURL: "data:image/webp;base64,UklGRvQAAABXRUJQVlA4IOgAAABQBgCdASoYACQAPu1sq0+ppiOiKqoBMB2JagCdMsp0sB1EyzfSbl/eb+N7CbOjNandh31G7Nj+DoCAQAD18Wk2M7shtne0c2w7e80w/tLWZNWX8ylCyCnwmslo4Z5Qs6nt381kmj0kXQ+Gt6ADRO2VdNe2BxB0oXhDFwCoh966D4TnzW7iuPVH9Qei4R7M5sz9u2nbBXfM5yi+Gw5nPAQwwsCgi4Wdhne/rqZb/8CLMyMGjZv/WSqigl8cw3guZcggxsf217TMfecgUQ8We4Cgvp+8ZZseirKJcWzUnEcjA8XGmkErqoAA",
    downloadName: "cute-wallpaper-for-christmas-12.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-29-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 29.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-29.webp",
    blurDataURL: "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAACQBgCdASoYACQAPu1gq02ppaQiMBqqqTAdiWgAnTLCQ7Ab9XIRuy56TDqr1Zop4a2I7s1BuMBen/BLDAAAAP7TCbMpnb4OsshwITwYxGBMcSx4h3tb0gyMKPXFK1rpQZknifnkVkyDX9rM3WTA15FWNPI4kuIq69FJFrU/CdQo38eK1U9No8Rkh3ychowHG/Zt/qSB5mCC987BJ9yh9wpyPH+NFhmMag4bTLw5yhJ8vkTERj4q3kAA",
    downloadName: "cute-wallpaper-for-christmas-13.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-30-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 30.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-30.webp",
    blurDataURL: "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABwBQCdASoYACQAPu1krE2ppaSiKqwBMB2JaACdMoSFAB39e6KEOdXK5a+5gcZOcxcsXCMQAP3amRF6cMifZYlE3sG4NEaufAlGcTOTM9czZnIV0D/EDSKXSSwgjI8iQsPLkQclABt7WfP//Jyy/FWlOu0A5t7wWYwdF0R2rpuhKpwXjfzqhiF+7HT+W722InDKIr7D1eLPipe1CGiMF3rAqmwKKUYcdvF2PD8EYxNlngAA",
    downloadName: "cute-wallpaper-for-christmas-14.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-32-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 32.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-32.webp",
    blurDataURL: "data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAACwBgCdASoYACQAPu1op08ppiMiKqwBMB2JZACdMsp4aCrKs2iMjW7lejy6GwCKFFxZqJ+cp19TDrQWTca6AAD+l3TrksgFJgcm/DAYuGvDVaD+BAneD9rAYq5BhQKXBDZVmNiHGppOuTp0aB4UgRkemKyoMdOgBuopA94hg9FBymIFMkpMw0bEi8zUTELefAfZtsoRaZJxvgGrhwoQ4oV1fcNVLs9KwJoShz/eAC3JhEakCl4K0wMGVIYj9drKu0RB7A/zqb3xFOHoBC9t9pdmOSMIbpv9TmAAAA==",
    downloadName: "cute-wallpaper-for-christmas-15.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-5-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 5.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-5.webp",
    blurDataURL: "data:image/webp;base64,UklGRnQBAABXRUJQVlA4IGgBAACQCACdASoYADAAPu1oq02ppqQiMBVaqTAdiWgAtvuWug6yz8E9MbELQpKqMZqLyFB33NFguWccmk2TUcJT9JHBDCRwq1s1qVIkxIytAAD+IFpOD+/G/xUmrwd2LDAaCW0dlzLvXOJ1J9uv8ij+hkRdtb7VhIhMQUM862eGMTKrBO1Y/sOI1IAkqqLsd0G0EwffNG7RNAc3Mjrzy3ixISwulEmRtW/DGXodTbwQ6oRmgu9b5FJhXc/8lJhZiY6x4vObQl1ugEqplqzFUlTRfMjWYiER9w6cUJjFbPjKwFLhKGglCeHvUePlCtUgvXHCM3XvjwE/yPXGFFJVxfMaA6trsODkAcIhSVQQof5XrJBgO+zhj9IQZy3NL0ovcBbGfn0mpEKaIqa2RkPZ7cysylCXtAlY2xjJcNQKMEbzPlQdFhAYvPpzh3DLv7Eh/+wInRgAdNnXQMY1X8ViCWr/ZwS2OSMGw7oAAAA=",
    downloadName: "cute-wallpaper-for-christmas-16.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-new-6-png",
    src: "/wallpapers/Cozy Christmas wallpapers/new 6.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/new-6.webp",
    blurDataURL: "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZACsH8ADG13J6syLnxQz/4gAAP7l7I9CsLdddjevZaRpBmFfWEM/8bbmrjtoaeuwjHvFdkZjXw96bzei6s6y0/7DDInl8AA34ALG4+R3dt2eK+Oj2YcAwkBHvSkbQWv/DSuNMUDeSM4QKuYQyflsxxzhoPWJHjUBaGBvwfkDRb4RQYBRwAAA",
    downloadName: "cute-wallpaper-for-christmas-17.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-1-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (1).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-1.webp",
    blurDataURL: "data:image/webp;base64,UklGRjIBAABXRUJQVlA4ICYBAABQBwCdASoYADAAPu1oq1GppaOiqrgKATAdiWgAuyFlHABNqLIpHR2227TSsYqmI2IFGEqNv+wnGjRvFT4Qy0FVPYkkAP7oue87CttIgScUixHMwxHr4phNARW9URNs7zTjmlQ1Th4L3Ixg8XnDBISPxd4Elaqlwh8TkBxQWoCOTFuUko3hfaCfYD35S7J2aNCrAS8GJeL/PJ50Z9jgblDRjUgm6cTtQigFIUJbK55MLiasQxZQthHYGMiiRv9szjjTd7O1OdnN7BWh0FW8gpypDPgnYgpSU0Lg4H3xkrYgmE4aACjnKm89V8U40/ZH6Mwe1TZQGeDxujIa8/yusqVzJ04Vi1HW2oQZWWh+U/rdnJOcK4MsVZCb/u5ix0eFjYg/Kn6MgAA=",
    downloadName: "cute-wallpaper-for-christmas-18.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-13-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (13).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-13.webp",
    blurDataURL: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAwCdASoYAA4APu1kqk4ppaQiMAgBMB2JZgCdMoACbG7pe3Y+S5gA/uXrQdHy1L61BclGqv4Xj5IWF3GjnH7LJjVpo2yTL89jOW8bmfG1Pfc4UCH2qgQuoJTDz6RSGHrPiwV+uVb5otVR0qog7WrFkDPZWi/Vd+VAAA==",
    downloadName: "cute-wallpaper-for-christmas-19.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-20-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (20).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-20.webp",
    blurDataURL: "data:image/webp;base64,UklGRtABAABXRUJQVlA4IMQBAADQCACdASoYADAAPu1iqU2ppaOiMAgBMB2JZgCuTxG9mn/Zp9iN+DGBf+9hG5oPAlVmuCTBHeOGHJfsKUE7HPUZHQlTkLCICJv3BHliPm5AAPsJBWeEppgo1d+voKbqq+I7cYxFhjYPdQlGBwSnCZ1NElpzLO3PzU03RbM3jy7PiZXNN0PIU5y1Nnei2CTThVz95b64JENZOm3j9X6qfXNbo10h9+8SZFX8RT4OAxHwI3XfEXBp6YTKnx63lKeB6Tntf75A/6/fCz0zsKcnqNvUHm6nckMI/NN8xjM/6n/WuFhA63qBlRMH/VO/jI/nGCJDyRDZ7/MfoRJmjMbvyX5d6XyvysIeTpDupmmyX4iZp5KYNB3FAFlr1ryiZjjoGmgBjBO6X5oF5pF/7sFbIy9Vvrc+guPRlrF7IS+xDO13fCJcvMp/Qrm901HinB1Rhs5o1BY174tDc8sHlYqFok+uN2ZHJsKv7raq1nsAxvAkMTHHDzrG3L67uPTrR/woO7rD02mJEXr7HNkuMdFG16q5gCxdcIc7YKxcD5IeyzXapVq2RVvjs6Epp/Odb2dsEYfYL+E5qUr7rHdkTfPwIa9SPGQAAA==",
    downloadName: "cute-wallpaper-for-christmas-20.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-21-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (21).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-21.webp",
    blurDataURL: "data:image/webp;base64,UklGRpIBAABXRUJQVlA4IIYBAADQCACdASoYADAAPu1gp02ppaOiMAgBMB2JZgDDZ2PGB2C3GQOqlJ1247VbN/Jxf23jBgXck1YykNAN8gocMHtn0Zhtej93oAuHPCWUv1jAAP6nyDb7ddbk0agRyekKSW18qGwwh0+R7QL5xZuTCYBZ7m7lgTiYgQhWO0iGqF/8ozifOJ5Dc19Td3T3A7HJP92agZQBxV+buoZ0ydD4jSTGB0mjDYaGQYvAOIkl6SP2JU2wKhWxBzOLngxUu0ISDL1s9zd6aSG2h7zKBYiCv1B+99Gr03wU9oYexMjd51p1wStfGrvs+CI/NHC0s8Q/ShMT/q/Ih4b1PZ9NKXoUSJ0o9AX751KyiuJtAkMtUcNd7fzlUwt0fKYoN44AUZw2uRFdeZ474/H1ZCUWDQLytpn5G9a++gc6M15A0yu5FepDAV/E4W2kvqUVJ78cJBDTAunF/hUWyXLp+DJEQ9RjxJuC+M3Q3L5rT82bnr8eNRQrujD3seYiZHoXw4+YFfRAr4OJH9/gAAA=",
    downloadName: "cute-wallpaper-for-christmas-21.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-22-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (22).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-22.webp",
    blurDataURL: "data:image/webp;base64,UklGRmYBAABXRUJQVlA4IFoBAABQCACdASoYADAAPu1kqU8ppSOiMBqoATAdiWgAqSdtPC+BYaICs/z+wQdqzSn8jU1AcP0sTEBJOA7lb6j1nd4UgMeky/k4d68cuWAA/tpvI0cf9exyMi0EBms1La5L8JMTdQFF2/pUALnXC7GMb3+3wdaPIFeQmmTeXmFKw28LrVvT/lQbrHt/7pQjeAaMsrvnlicu7GY8Zenk93smzJ+ZLa8cy/ZOtH4i5LrVliOqxMep3vs0ykpj4wYw96/8LPsmE63JsC6NEC9x6CN7Jkn/FvA7NRB7NiQDDzCsCqmfTDdZEfoEIyFSJCkQDGEUbdFn2ajInSysfnvXgBU3Ddk4BYHJ3EKBEswx9UqjfROrgATfplPZn+M8+vhzZ6geApU7WNR+UWGv7CQBgQQdtW8r4dNyp3T3jq4ccfZOaVug5RcGRKfFieBI6rR4Dhu3s2UIJO/yCQFC0AAA",
    downloadName: "cute-wallpaper-for-christmas-22.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-23-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (23).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-23.webp",
    blurDataURL: "data:image/webp;base64,UklGRmgBAABXRUJQVlA4IFwBAABQCACdASoYADAAPu1cqU8ppKOiMBqoATAdiWwAnS/nyckALbVFte4EgYOopDUNwEv0wM3pjwzrq26jvjC2GlxHYRpcFAoLNa0+UwAA/vWV39v0BNZZKbnvj5QuFqdIgTYlBBzi50xtF9cem0tOgV3etDeOUc49oRQUdfFcNZeo2A1xa8k4DTXH79OxAXJCYyujm7AqwR9asVFvZgkntWJIqF8tBsawdMy7sL1aPILx4UhSqKn2M6iRGouRmUIC/ynNYCv8jfBkXCsbjUsA/2UBPWVt7+W3Wf/VFZNc6TYXJHjDACxYXvoHN6Xf+2wHmM4QfXQGd1MDk5Y6oQap/qMDYbT0NkuRRkjOygbPBP4fBnsXlkCc/lWdu4RA2HFIEkSrIBO8DvN4Vc8CG8eEtX92rHLe10hpd9SHtkuKPbjVkarO9zh4TZcKIPlUkXMHx6+T32F2ncICNjoAAAA=",
    downloadName: "cute-wallpaper-for-christmas-23.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-24-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (24).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-24.webp",
    blurDataURL: "data:image/webp;base64,UklGRnoBAABXRUJQVlA4IG4BAABQCACdASoYADAAPu1kq1AppSOiqrgMATAdiWwAnTMRrcGsDIv2aY2XAFnB3nTxqfcvCjmZqNH83OsnOMBTt1M7pJnwJseoiHpM/4AA/uzXNNNBr02yq+eRPnvfpgE4yaNyu5m5ZZbJ6A2QOjRMWfzSy66dpcoWnmMcFii+gT8XXMb90Ei01R2rAjFWFIt1yR0Gt2R8eYhlg2ADJfE0QrqtUhhBTvJjtOI2pornqMOBMerLZtxWLOIZZ4zcDj397fEy3fjmQyyY3+EAnRu2M9WlUCWsSkEV5h7kP4ZDGP4SNBAwDmjbS8mmgymqJow2gMqnVXtmPrMTm65xSkSDuefhqo9KDzcIwALRFWwrXxRdqtHvdywskmZtkCR+VBRBxPDUOzqoOCON4np1b8AatUM8GTOnnPXQOqNeQF0B+v9rgFz7NCr2/aV0bfqVDSQy852PYSvQXDz6Eva3GCNcnQWyGEC1CLH7HQ2e4IuAAAA=",
    downloadName: "cute-wallpaper-for-christmas-24.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-3-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (3).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-3.webp",
    blurDataURL: "data:image/webp;base64,UklGRlABAABXRUJQVlA4IEQBAAAQCACdASoYADAAPu1mrVCppSQisBVYATAdiWIAuyil2HixztkyWJzX9FRV4vCKUclU8p7tnVhXQk1UlHCbke6an0Ur9U9XQR9gAP7cE7ZEi3qudToE/0ObCHUiq6E0/B3QZunYpK3gN0Nxa9iznSHtb4YHo/t4Ir9/mzxhm5G72E/m7DW2Uze5usGGFtsQKC26rTP4CprpmRbVfuvxYRXGasEqd5NkstIIqfUJtxJ7BmVMYUNb1cTWPw1lp8yz6uU5zt9ohEDHYD39hBeAWSGLeHuO0dquYRqxBZrH+L5TQopQtY5Wa3w1mEAO6FRXOUeYLk4VazqCms6q6AwRZgk+EcpHKdjfDOW33/T1Osj/WgUrerXMJN6O302thy1n7wyhYOPfnbOLvcosYea9YD3mi02v8wRv7trJFvxGD8VoCzoAAAA=",
    downloadName: "cute-wallpaper-for-christmas-25.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-7-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (7).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-7.webp",
    blurDataURL: "data:image/webp;base64,UklGRqQBAABXRUJQVlA4IJgBAADwCACdASoYADAAPu1qqk6ppiOiMBqoATAdiWYAsuEGlua5g7F5bt0oOn6omQpar+U2IczfKKX1NKjxwX2Qw3IGWDiiuHayJKbnfjp/QMnkgAD+29qJIA2H6P+f3UHuPd1prc4YlTfKHHVgUm2dsrJEJ9EhrdsdOFwJemm18dKcP4za6QzQ5vosbw/Q6T8fi1yMiLfApy+hTlVhwQkz+3PA5nRGk+WYoxPhuWr+Gchov/vK010Evys4ZPN8zzi0indOcOp8/lnKKplxr88gjX/6r0TxUEeEKBsWAd8kse/hbngHB3F/5QQMuNfL8vYzo0/ZGy3knoBxTY2RWC9h/CCc8tEtNKrWP8wgIFpQxupHx1uE3FlpUb5dTSTtv+JgD9JSb9KXLhEtnm179vU2f4lBFkjC+UZRcBkjG3WR3eG0TknA3BC0b++UblXLwO/0nBDe4s3ge2cfbfXIZafx3aq5WRnOD4/m+CBx4VkG1CJC4o2ToFMkm7o2Ot4WwnKmVYlRsFFRZ/LqlkDoGYUzIi74xmDwCdfCAAA=",
    downloadName: "cute-wallpaper-for-christmas-26.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "cute-wallpaper-for-christmas-out-0-8-png",
    src: "/wallpapers/Cozy Christmas wallpapers/out-0 (8).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cozy Christmas wallpapers/out-0-8.webp",
    blurDataURL: "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdAYx2yjnM8ADLedLP9JY0vAAA86XPdy7RHeTd89KokPNBjU9BVf0NkMTB96Bgh+U4Gm14XeAs0+SMS9m1UaabjfDP2bAg3PeLMPoGQRKPRJ+zTpwe7KFMx2OyYg8Dyk/406GGCwWRP+O14KjaBSUXSPOzSRFV4U8W4hX3Q8+lEWvsxAAA",
    downloadName: "cute-wallpaper-for-christmas-27.png",
    alt: "AI-generated Cozy Christmas wallpaper",
    themes: ["cute-wallpaper-for-christmas"],
  },
  {
    id: "winter-cabin-at-night-wallpapers-cyber-steam-punk-01-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/:wallpapers:Cyber Steam-Punk 01.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/wallpapers-cyber-steam-punk-01.webp",
    blurDataURL: "data:image/webp;base64,UklGRhABAABXRUJQVlA4IAQBAABwBwCdASoYADAAPu1kq04ppaQiKqwBMB2JbAC/YIEbGu1VsKWGIltTnlRd406yM8OCyMJJrYhFGVN7Zsdx/JDqgkjUAAD++3gszNlMgAQUt5cL3LuWifxf+DJye5dfZpGBeJD7+3/VkwK5+rnf/WJ2qOV/KLIv6dnJuB25uiBfZ4vDzGUvwdU5pFIFrVZTFDVfk9adOnTexj/Inx5AuylmC5vs/KXykpHfLeo1hb9GQUFVa9f+nopNsFSPqpMhpMvQTaycqQtDo7n0akCm//TsUHlg4SJuq+bAdZQdT9c+v5H+o2CNLZyrPmDN7a7D1qRxMvdf2jumQT2F5YIw5mfoQC7IAA==",
    downloadName: "winter-cabin-at-night-01.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-new-24-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/new 24.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/new-24.webp",
    blurDataURL: "data:image/webp;base64,UklGRjQBAABXRUJQVlA4ICgBAACwBgCdASoYACQAPu1eqE6ppKOiMBVdUTAdiWwAnTLKcB3HgDRsWaBZBte53plBOdJurmL0fs7cAJ4V/8+IAAD+8yBenAek2e45UXv1k/HMmyGKL7ota5EFeoyo/XIms5+8OGhjiGLH5LPdj7KzcPNZDbzsc8tHO+qeL9dTOdLa5fVEGuLwqhV0dWelmo5KcQUnAAkvFH3lgePLbWsnzz5u5u2w4lb23Kd7XuoX2mUL3X/ZhyNOYpyP6uPGa5KyUriijLStGe2yFv8LoMIV97+e96R05EDT477vujFOBv9hDw7BLXiAaZpKBzT3K8RTwzT2mAJNTnqbh/r7e1ksMzrob8ivdNAExIYjG82J1a8RtvMc8fEhxh+IbLklZH7HGBhkJ0HPDiQgAA==",
    downloadName: "winter-cabin-at-night-02.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-new-25-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/new 25.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/new-25.webp",
    blurDataURL: "data:image/webp;base64,UklGRmwBAABXRUJQVlA4IGABAABQCACdASoYACQAPu1mqE8ppaOiKqwBMB2JbACdMsu6ZaA23d2AegA43VlcwmR6gop7HlOKVjFCEi2MFoL2Zq+AqSM+7tnF9Sm50aAA/tHZhN7aj1/irbM05x1hr1ATHIJv+PYLSe/vAR7DKAjP3sT6w01X7BrlEAubiNESqwDNtiAgsQAGuMogrdFSaPuOxgskg0mHtxKXVYcuP8sBC7zd4jn42MPD9/9r/d/2FgJ9pRwzG1kgD6AJDabti9+RmFZF2dCLFQutBd5NM8URt88slsPUtYnaQy4koqJcg1Oc4U/eLuYTtTelaXsVtZP4c2y8JWKQWpkp34gutIVABzMcvHGhfA+AUU+0JQBC8Vqr9+RvoV8Y4z3pkVYJCZd0NXEUb6CeT2JMdFO2WPyVN6QrLQNjEWO9I0kn37U2gUJkvY/IT8yHj/COe17kq79aIs3l+db9z0Uh91X6b7CQAAAA",
    downloadName: "winter-cabin-at-night-03.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-new-26-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/new 26.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/new-26.webp",
    blurDataURL: "data:image/webp;base64,UklGRhABAABXRUJQVlA4IAQBAABwBgCdASoYACQAPu1qq1AppiOiqqoBMB2JbACdM1pBgBbFodcKcqXYS5e1FjDsiqw9mq3ZtDtW9FClLYAA+59sQmjNwLXoxcYUgo9vzqkd5xKTBI4345kWOiwNdfyyHOxnUJfKo8uRXyjrrsCXDn4kMPEpjrmVLFEhuNH/OiSdZFfQKy+X8EiGuhD27BO1IIefOFD2JzJjdz/NRJg0GmslVYiqnjis4f02rAIJk+R3ccc1oQG0SrtsKEBLccCjqCbzj8qYG/xERMC/ExJYlSh6Jd+i1hXkkTZuY5ZM98j21Bn6kwwzvDtw9EAppynXBCgwqo2chbGFfpeewDTRyAL5GvgAAA==",
    downloadName: "winter-cabin-at-night-04.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-new-28-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/new 28.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/new-28.webp",
    blurDataURL: "data:image/webp;base64,UklGRvgAAABXRUJQVlA4IOwAAADQBgCdASoYACQAPu1srVCppaQipWzJMB2JZACdMoSBb5SGQcWXlp+wiR1+e9QYgmURDRjQNpKydpTPVJDr5AAA/s1D5kMS8ki3t8XO4cykzzn73sLPx2JfZAwO1b0/mCoYU/XJKoQXgcoTv9Ky6nBC+ObrCrbFxt8jMKLFZpdjI83+6KM0dQooXDXMs9DvZpUrjqvdXU1VSJDqfeEdT8E6+MpFIi6l9h2rIcIUoP3ymD+El7CHJ9ZCzuwND6xPks35jVgLRAJ8P5AEpyfpHiukvWnj4RspYooS+3BaEDbVqqQTiACIUKmQKtbAAA==",
    downloadName: "winter-cabin-at-night-05.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-11-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (11).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/out-0-11.webp",
    blurDataURL: "data:image/webp;base64,UklGRhABAABXRUJQVlA4IAQBAABwBwCdASoYADAAPu1kq04ppaQiKqwBMB2JbAC/YIEbGu1VsKWGIltTnlRd406yM8OCyMJJrYhFGVN7Zsdx/JDqgkjUAAD++3gszNlMgAQUt5cL3LuWifxf+DJye5dfZpGBeJD7+3/VkwK5+rnf/WJ2qOV/KLIv6dnJuB25uiBfZ4vDzGUvwdU5pFIFrVZTFDVfk9adOnTexj/Inx5AuylmC5vs/KXykpHfLeo1hb9GQUFVa9f+nopNsFSPqpMhpMvQTaycqQtDo7n0akCm//TsUHlg4SJuq+bAdZQdT9c+v5H+o2CNLZyrPmDN7a7D1qRxMvdf2jumQT2F5YIw5mfoQC7IAA==",
    downloadName: "winter-cabin-at-night-06.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-12-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (12).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/out-0-12.webp",
    blurDataURL: "data:image/webp;base64,UklGRjwBAABXRUJQVlA4IDABAADQBwCdASoYADAAPu1opk4ppiMiKq35MB2JbACxAQa5+DdQGVza6TdZqTU34LH4kMdDzCEbY5YYeH3l7yCGlRgA7brhL7OooAD++3l/GDyXFiLL8TF93soUrBG7lMHhzBekusP1KTwoW1yGCMrsLTWRFtW+siSkhx5PN0hgZdjEvUXJrSfOFCUICPH2brOVh8xynt/U9pJfvjOQCH6Dk0ODC5L1pVxGUDKFZVN4eygLUYmgw+TIElOYABIq/xf0l1WPgQ73JVRw4eCxH8ydcbVqzTJ0hQMjSzA2X21cohFlCzPggSPQKglTscc2CXD+1ZqmbXlE9K1MTjhXU6WBJrWixGzAFnnURp43n1qk2B9IgGF8fege5bG79q0KdZgY4Z+Iusu1aAcOQ6TuIA8mKwAA",
    downloadName: "winter-cabin-at-night-07.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-14-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (14).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/out-0-14.webp",
    blurDataURL: "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdABke/gk8j7dBC90RgAD+5m4f2Iax+1OzxXJzIfCZf5n4rIYebFrVVJG5TZa1lV5sjS1PFUUaa5YtT38QhLOq4DwNfFptd9/V9o1PUS7hE781uceryxjDopfZao9QPbQSHvcItREmRZP4sC8AAAA=",
    downloadName: "winter-cabin-at-night-08.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-34-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (34).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/out-0-34.webp",
    blurDataURL: "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAAAQBwCdASoYADAAPu1wrlMppiQipWmZMB2JZQC+wFzn2VT1gm1+CQE5RrHk9az0okL1dSMsgxlH9vLYEDNKlKBrgAD+8X2LqYk0zyd5rxd0fwyqLwcZHR5HSmyhplqFIk9jz1T6/xXfmgRNVu+DOORECMDvBF8ZzqLSnYYM2gPDQV59ORX52iI0bgXoaY55LN3TjGykntoD5H5h7KocSVqzj2JXYfT1YEQH81VsOR8ZkA4gMdBsxpIc84nwPau1P8XjsjUrnPLcDJl95spO1X/2rlJXZj6+ec/gejtlUziJZ/fxirJeYH7UQXRL7JzMAAA=",
    downloadName: "winter-cabin-at-night-09.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "winter-cabin-at-night-out-0-35-png",
    src: "/wallpapers/Cyber Steam-Punk wallpapers/out-0 (35).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cyber Steam-Punk wallpapers/out-0-35.webp",
    blurDataURL: "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAACQBgCdASoYADAAPu1kqlEppSOisBVYATAdiUAVJPFBSNQzuIPWMCvWJAXL5RAeVepP5X05iLw525pfB8ggAP70va7RPdiusIg+4FXOgctGNecXxB3QHFj/2AOjVSge5mlgd8HF+lSj2N9pS4GQfenZ8iDg9OSzQhYu5ZAUWcGT8k4hCkD6TcMxql7DlRAWtctTRWGWJqjBnz22rgJAYOyWwTNoQsyYwadrxybGRcJfzzq/+NfaZA9/EDXBAE3v6rEG0NwWJH6tlyIPDYyBXAlXtv6batMUTBiuk6QXWajGYfBosQOdKi3ZBb75oElHQAA=",
    downloadName: "winter-cabin-at-night-10.png",
    alt: "AI-generated Cyber Steam-Punk Christmas wallpaper",
    themes: ["winter-cabin-at-night"],
  },
  {
    id: "christmas-tree-lights-wallpapers-christmas-tree-01-png",
    src: "/wallpapers/Christmas Tree wallpapers/:wallpapers:Christmas Tree 01.png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/wallpapers-christmas-tree-01.webp",
    blurDataURL: "data:image/webp;base64,UklGRnIBAABXRUJQVlA4IGYBAACQCACdASoYADAAPu1mqU2ppaQiMAgBMB2JYgCdMxMIOEC+WBGFpy6kbT9lTnO7iLW0iE3Ymidi+4WhCUoZIIMs9Zm7TdoJ5KJC+9K9AAD+6+xZMTqDiiRnXYJNRxO3XpSo9RNP6ax0fp9HTdYRDjdxgM9kEUBMUE8gdfHNXu+vyad09vIRJpp94yUK3Qthde2lJLB9d0Dv6MlT13z78wp740JAVPEeSS5QlWa8aNhRNsUL6uAc5cgGmff6qsQMriSw6Bw3Iixx4DxhZM5Ugo4oA20auQLmyWq8m3CyhyvydfUXFOH0hcHr9DHZVASMzVnBCzXdX1/2bcU7rW/qG9CSZodUcjp5wlu7erw3vWHdKq1sHv1ucjUD3kXc6Qr8qxIThiXjWLtJTZnbfyMVrlP+vj10g++QHQDyttFpAbfl/n2om9eRyzwcA0KBMauQvWEWo9rLPIZgZl7XXxX8ghN0+D5hVUAA",
    downloadName: "christmas-tree-lights-01.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-20251206-0937-cosmic-christmas-tree-simple-compose-01kbrmww7xekcbv4ez6224mxe0-png",
    src: "/wallpapers/Christmas Tree wallpapers/20251206_0937_Cosmic Christmas Tree_simple_compose_01kbrmww7xekcbv4ez6224mxe0.png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/20251206-0937-cosmic-christmas-tree-simple-compose-01kbrmww7xekcbv4ez6224mxe0.webp",
    blurDataURL: "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAABwBgCdASoYACQAPu1qr1GppaQipWsxMB2JYgC7My/EKFuE9hAvQsLZxr5U466TPbzS7SlL7hZnMP3s5AAA/IWF+mrJU1en1akh0qCnohaigG4xLgtXOJdgslwaqxZV0sg0dQeY788YKyPt9MqJXpZkptslvtPn8Bj9DvmzOkH40yFrtRLAzKQkcaP6BVs5IgARKdl4aqebE4YCzFaKtzokwB2DV8oG+Mxgj1PGxV8M+DoOj+doVkpAfMAAAA==",
    downloadName: "christmas-tree-lights-02.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-15-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 15.png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/new-15.webp",
    blurDataURL: "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAAAQBgCdASoYACQAPu1kq1CppSOisBVYATAdiWIAqSdXb/4FMuTI6g3rhe03AXjO9QCKiqgOXe51LMAA/uvos8qz7dEmOhzgJYuRecZBFWW3MfhnwnhAogI9IhZzHn9c7GzvT0WDR3GD4X0jkL8PO3mxSxtBYqK3Justxe7QeP2U9yso8fPwK5eZhTFbg+3N96BCkzUKVK6p8i4vplPMBOvchI+/tJU598FvrLszovNM+2dCTHdux7LC37DosWgA",
    downloadName: "christmas-tree-lights-03.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-22-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 22.png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/new-22.webp",
    blurDataURL: "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABwBQCdASoYACQAPu1or0+ppiSiKqoBMB2JQBXJ8dhF83Tw0C6BzIaYyyfyBIC7tt+OAxAAAP7yohJMQaYe1MmgEgMIcQqMFTrKXgvR7SIrYFVepTM3Xag4cgogbQ3upEnYjeeM5JJt0IN1Yt58FaC29PaShHAhNhFd8eOyqkun0q8QJi+4CZzioGBFTpz4ce5nggCZBFAAmwASF5OVk262natmAL+cd6W7M/82gAA=",
    downloadName: "christmas-tree-lights-04.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-27-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 27.png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/new-27.webp",
    blurDataURL: "data:image/webp;base64,UklGRi4BAABXRUJQVlA4ICIBAAAwCACdASoYACQAPu1qp08ppiMiKqwBMB2JbACdMv/6t7tc/sh/UxtyeeQ000BvgancUTMQTf1AoU6/+kIZ0ONrDOdBZC+JyvpxgAD+zW02FVJnGOlRLlw+AzT23FxrJUdeYj37qudF40f7SiaT8zxCOHTxp37AVcr0rDaX8mtGAgPR3oGNUH5qSlDZk3lz5iA4dKOJ6L2yBcCiQiIaEptT2L7cnpTww5VQ2OsQIU/G6N4NpGRIjFfOkMqGFMm35INZv9sMQ/BNx39RXG+GVQTMENfhhSuulDfCDKSo1Dvxtpwe9C80azOQPi029QSxO32vHUXZSJ2E9z03h7qObYJRqlqiuG/4n/bF3slH0O/sLLQgHSqaNDdjNYOMI6dk94sgAA==",
    downloadName: "christmas-tree-lights-05.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-3-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 3.png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/new-3.webp",
    blurDataURL: "data:image/webp;base64,UklGRlABAABXRUJQVlA4IEQBAACwBwCdASoYADAAPu1ip02ppaOiMAgBMB2JZACdOUFXPk05Uz508xKMHcRXp/Wrglq5czMBWhT84umDplL1W5Clqp3+s0CAAP6BR2A0cdUjXDJpW8+H71wmhCWGRhSZ6n3cVlRm6NRDCFxrvsxyJqBbeK0ofDdql6/JGGV3Q5s31m/mwTpj7afqa3YmvaupXiz2ldsPz5in/BkhymrHU479Xpeoiq0kJNdhSLJBH7fbgzG7/eG5+k8OmH4tvOHUVF3dod97Yc22gIJVsJKXcEKqtW1vIiBY9y6Bu8i6zjfRyJjqIgWHIFVlHAHZfqwA5wxYA6uZ65CPngysbgF79lh70xShl3gd8iAhi+gBW7YqfZx753vpHBTCF6muRP1z/VH1hsCfWJzIFTr4vn0kGYQjbKLCcECy88fTat73t+F0rKZ1AAA=",
    downloadName: "christmas-tree-lights-06.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-4-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 4.png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/new-4.webp",
    blurDataURL: "data:image/webp;base64,UklGRj4BAABXRUJQVlA4IDIBAAAwBwCdASoYADAAPu1mqU8ppaOiKqwBMB2JaACnRxG9dI4viCCDSlx46EbYNwUUXD+28Qt74N7zVAVsgGFFP9JzvVgA/tlaK/tQ2BZG85zs5VWKAtPqVh3By9vR+Um/1E7XDoj/1K4s7eaUQhNQ56+5Qa/Mr/RMpCxX71eiEMzhfTgX3u1rAjNZ2SYhv4v0EbSfXtvJkV5OTXnBm6yY4dXZsDaQIbAB/rLIBQW03GyxKmFuHxQnyFcA1JZz+6Dz1j3f/KZ2cs6EQqiwGDAqotZTc8LIw8mDcvdQtMpd/OZv54DHAi1exiynD6nnGignDyZPLjb4WGGu+FiBAULcoNBUAD1difyTDNYwVovjZhCpNAaW1n5FcYoq5tjFXtlj9ZGRzeYzgcGWstzhS+M4RgeQAAA=",
    downloadName: "christmas-tree-lights-07.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-new-40-png",
    src: "/wallpapers/Christmas Tree wallpapers/new 40.png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/new-40.webp",
    blurDataURL: "data:image/webp;base64,UklGRu4AAABXRUJQVlA4IOIAAACQBgCdASoYACQAPu1mrlEppSQiqrgKATAdiWQAnTKEf7AdA8hVKRzKFtdrKfs9tA0J+LJiJE+QIy84gagAAPx9WupSw1Pl/hQzH7lrDNT7frlSYtrEHuQ/z3mAhHOXZQ7ZZ4fzGJzI7D6IobeirLzNSpW1Q3Xtgwg97kU7XitPE8GZonlw+kW9U2vUeAt/+rBQzBHRsHDRhBTTUVGq3JaN4LjEN0gq15eqXTllfYAxM5NzrW/gg2xkGJOUy4q/gU1pf7JfQSMUqxlYY+rDkaDTU2HS76wcjuLbNdPt4eEszZgA",
    downloadName: "christmas-tree-lights-08.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-out-0-36-png",
    src: "/wallpapers/Christmas Tree wallpapers/out-0 (36).png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/out-0-36.webp",
    blurDataURL: "data:image/webp;base64,UklGRigBAABXRUJQVlA4IBwBAADQBwCdASoYADAAPu1mqlCppSOiqrgMATAdiWoAv2uOg9ggtYA3qYgIlZebHcbex8KJ/VpJGr7YLlAh30viC42lO21njC/uwAD+8Q0Rs7BXpAhCXlaswZRA6zvd5K2hMKWurKzuMHk+vD6jq49HAsrHuBC2f08JWMJ/MBbjxwv1goSY30EoN5bIrQvnCGrJdhO47jZFmnY0FvoEjlTucoea5wkf/ZtqUpBo2ioeUqaeGxJN2sS2VOFjM4geWpMjpspHExr6EvlPKnu1Gfk23KUna5JWnx1yWy/xjmUvm4dRvmzdlYQvRB6haLjBI/UlbZI4WLIzpRCDreR+Fq2GID7VoZiayABbAkthf7h846vvHgGkze8xWl2gBpPgAA==",
    downloadName: "christmas-tree-lights-09.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-out-0-37-png",
    src: "/wallpapers/Christmas Tree wallpapers/out-0 (37).png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/out-0-37.webp",
    blurDataURL: "data:image/webp;base64,UklGRhoBAABXRUJQVlA4IA4BAADwBgCdASoYADAAPu1iqE2ppaQiKq35MB2JbACdMz4H7tRUunGBCQQ0MUSlvMlrliVgEVjm4T+hkSaDggex2f2QAP72qZI1qL+GaUHrPiPQO7VGjBNw4agMoFUCMxj3DZooEtDLjW/GaE5oNvnY4JJzDepLE/nrK7waRodus9cUg0IX4xCuLbIq+s0R/L103bsd1uKjcnbN30ojcrODtq1o7G9Div1te5VQADr9jJXsxGbL/o6wSRDP4w2K2DzMhKrKSVUDaN71C1YzURxL3WrIDMsQPlJ1+7Qbxca00BhW2Q90wGgzgYLzHzEiYD+MWOu9Zi+gjMudCeTWBW8WyK5p07Re3qg+8xZBGbdYYAA=",
    downloadName: "christmas-tree-lights-10.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-out-0-4-png",
    src: "/wallpapers/Christmas Tree wallpapers/out-0 (4).png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/out-0-4.webp",
    blurDataURL: "data:image/webp;base64,UklGRm4BAABXRUJQVlA4IGIBAADQBwCdASoYADAAPu1mr1EppSQiqrgKATAdiWIArDMOSIHR2y7itksDnXXqcJ3wljY+8g2xXTh/exY0I7akptgxvAyke1hrgADLR80SC1n8o5hhrlyhd6PzTXF3YFUeic4cHAMiSROGxceXvYprGep7vOOFFarRQXVGg54OqQ81MxdtPI32yKd8FWih4CRaesuXbNpYAhnAyx7x70Ti1Q8vc4vlLTaHjayvCnSvpTevEHRzW9+mYaBJTDjHsGuPg0BUluMLUagb+Tt9s3zII7dgOMPxCt0rmVDT3nuDCEVWrO/RZYO4zGyp1XgPcDzRtTqKB7Jr9fJ4zooveDQLKtCy+hFKnZS01RYv5wTpxEvhJ1A97ey650OcbjB2hYr3EUHgKGC/GSKrJc9QlOfXnQKShlaI57ltKC1Zqav+po+kVf/3YbLk8L5jox4VVfUxz0GAEaKfOC680UL4/z9hNGgAAAA=",
    downloadName: "christmas-tree-lights-11.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "christmas-tree-lights-out-0-5-png",
    src: "/wallpapers/Christmas Tree wallpapers/out-0 (5).png",
    thumbnailSrc: "/wallpapers/thumbnails/Christmas Tree wallpapers/out-0-5.webp",
    blurDataURL: "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwBQCdASoYADAAPt1coU2opSMiNVv8ARAbiWMAwCgbIHmYAUY4KJCN1Ct4BMcyT3MUDHsShSEHQAD+5l+prawYziz108vosiJRctIh9XyO78ObCGPpO+Dvmhf7psFO6EL4euB0dMVKbe8srnl0JomvGOuQAarBLF5/JhiUAytA9bpZn/dXnshKzTeBauFJWW37JFF/7grC2+NdhT9uxzNd+wQAAA==",
    downloadName: "christmas-tree-lights-12.png",
    alt: "AI-generated Christmas Tree wallpaper",
    themes: ["christmas-tree-lights"],
  },
  {
    id: "ice-castle-queen-20251205-2039-epic-christmas-warrior-simple-compose-01kbq88ht5e03skn5sj4c20zzv-png",
    src: "/wallpapers/Horror Christmas wallpapers/20251205_2039_Epic Christmas Warrior_simple_compose_01kbq88ht5e03skn5sj4c20zzv.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/20251205-2039-epic-christmas-warrior-simple-compose-01kbq88ht5e03skn5sj4c20zzv.webp",
    blurDataURL: "data:image/webp;base64,UklGRjYBAABXRUJQVlA4ICoBAABQBwCdASoYACQAPu1oq1AppaOiqrgMATAdiWIAnTNpDnkR/W1BoyAvwnF5LoO8/6ejqnFK2Wqrah9qNGY/uJn0Ca6gAP7QwJvHBLfS8ssUAk05WqRoiCQcGf7x5zIQl6rIsmtzPHH/TdzYhSXUGlAttg6texBegskCT+7jBgeBehNzHvEQvOH2204hrdXonkr9PTw3zJSCOq9A02VfKm+MjyIPjyqkIUFByJQIl/ILV/TU+M82ZBpTosNqa6OdJ3eGP/Yj2hUybsmQ9u9CSW1yDIfBrVsgpEHiTY+jH9W0A9lTL9nlSPJePy1avwMAVtRwSPWpYOaVUKdB8afAaqNVj1QSoW9d2WWqfWhBkul3qX6Uv7UuQjiNprT6faImNzYpt1xg7Q56AAAA",
    downloadName: "ice-castle-queen-01.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-20251206-0015-manga-horror-showdown-simple-compose-01kbqmmnkhfdcrst3rpbr8w1q9-png",
    src: "/wallpapers/Horror Christmas wallpapers/20251206_0015_Manga Horror Showdown_simple_compose_01kbqmmnkhfdcrst3rpbr8w1q9.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/20251206-0015-manga-horror-showdown-simple-compose-01kbqmmnkhfdcrst3rpbr8w1q9.webp",
    blurDataURL: "data:image/webp;base64,UklGRlQBAABXRUJQVlA4IEgBAADwBwCdASoYACQAPu1mqE8ppaOiKqwBMB2JQBe+IYf/iklQQLgFU2nB8hiFPzmmtoniDDkoSkx9XEUDb5UNU2sjqH4V90/KY8AA/rDWfdvD40ACL/1zw9sjEi5dGSk1D6TFaWBwzz5OP9BbI1KninIxEgmpuSPdKK6pD/MD1zbm6w6rcqHOfyv6vc9FjtfzxnDOqRRnnJcvC/TR/eue0w0Lw4wfNuo+t3wJZ/2t/2mtXggvepEldNNYXOqzzP2tZDJ5ep7xLah9kFvK2r6BhsLJFR5X7C/nuwXZE49WDnKXJ6+XbzChSAwo0opMzlsy5zYtbXEhF3n5htvbROlsjwoZTYA4BYeMVoCvvSVAUrjy1BixW2sjs8B45fqYAumizOtLcIBXsOfKdfrJB2Wcuri9dMKicT8zOt0j9FZGz7kW9L6pY4BGIMAA",
    downloadName: "ice-castle-queen-02.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-35-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 35.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-35.webp",
    blurDataURL: "data:image/webp;base64,UklGRgYBAABXRUJQVlA4IPoAAADQBgCdASoYACQAPu1or1KppSQiqrgIATAdiWgAqSc5joUMWpqrPH594zf62G2lOh1Y35iGsePHJ264L8PmtEwA/Yw635F0i4RCXPQ2Y2xNP1N62RcWfdlw2D8lQETP95SKZoU0sRCy+EtdEiUnj4l0BSfF8M4B02X5nN6GGoFgT3d818W/4FI5aq8bFj9Pb27tSL/XJNQV6k1lWQe7Mwa8hMMgimmwk633QIqupAKmt3BR/SuSqCXXcT22c5bklzKt+WDvulBgW07mYfk85YHTeQyI60YkCF+4GsnfpJQw4Kh/xO+0ePVoWz6NGEzmarP8IDMvrqp0eAAA",
    downloadName: "ice-castle-queen-03.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-37-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 37.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-37.webp",
    blurDataURL: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoYACQAPu1orFGppaQjqrgKATAdiWcAzNAPFqs2cCwK9xBA6QQAAP7wJVpN0dM+OQnDzMRCdWpaWjI41ZMI8qiYcgVofZVNYekWKbyoEXZDVQpMMnXYAA==",
    downloadName: "ice-castle-queen-04.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-38-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 38.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-38.webp",
    blurDataURL: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoYACQAPu1wr1EppqQiqqgBMB2JZwDFyBANNz1wEUYUAAD+8rSudUBfZ7EH6wbG/se1nD/PXhkzjnL9pCT5KcESmhKuTFeLstvwTsdfC1jFYVl73/Zz3nyS27vR6OG+FDTiSY7rrT1DbQKxkwAAAA==",
    downloadName: "ice-castle-queen-05.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-39-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 39.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-39.webp",
    blurDataURL: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQBACdASoYACQAPulgpU2pJaMiNVgIASAdCWcAwNwgQ0MxBjXEDnubY3AAAP7w+zUgoOUtIKE/NNLKlI6MQSz7TTY9nr/2L3hDBhMk+kvstkBRyVrxntC3G7Z2pXjV9xUJw+h63YINn++5KsUAAAAA",
    downloadName: "ice-castle-queen-06.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-43-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 43.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-43.webp",
    blurDataURL: "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACQBQCdASoYACQAPuVkp02pJiOiNVgIASAciWwAtvuDvbgrpwtu0M9Eo39rDwRMswEZ7rYQAAD+9XvhZDnZXmg8kCuxwKhfAMzAoisGevrfxNfsXu0uxgZwJO+nD3vnt3YK2GfphIN4LIgkx7JxEUCcmq/WiZ/rXaf8vweDjhn3coztlJzosoSb8LIBRoAMojvXs8CTNBhJn9YcHJJORyia27P9ygAA",
    downloadName: "ice-castle-queen-07.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-46-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 46.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-46.webp",
    blurDataURL: "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAAAwBgCdASoYACQAPu1wsFMppiSipWmZMB2JQBYdhAm6JoZNfktz5ZNlLs71f1aX9NgG1DtGkm8jG2ngAP7qIqSriJHDkqjYbbu2SgGr2HoM4aS0kJVCEcxdXdWPwWuILMe1j/Qye74W5HhZ3tsiL7fA9einywafgjhWgKJrqw5kIM15bKSRaEptaGaphdm4mm3KhICdBVewv1pVJWnbtWL1aYi/BsIGcR6jDz9fEbMpVPgZz7rNfaT2gNhaF1vwOIOMVDFeXzvEjRF5s4q4HiM67shIk5Bs4A9G2cA0+tH+oWV+pEyAMidHliueiFeD4AA=",
    downloadName: "ice-castle-queen-08.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-47-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 47.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-47.webp",
    blurDataURL: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACwBQCdASoYACQAPu1kqU6ppaOiKqwBMB2JQBfJCL2tS6bKqykmCrIpJIYz6wAApjOy4usJOfAA/vnIXY1QePydnx/jmdp63uIHP+nkIWD/DCLkItKLarAbEkKHt7fvAH4+lvGGxrviKOhVAPMGxKc+7uA9vw6DzRvy4SuRnPgf7dQ+DAvP6sj7dKrXvlIjAT9d+AAA",
    downloadName: "ice-castle-queen-09.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-48-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 48.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-48.webp",
    blurDataURL: "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAADwBQCdASoYACQAPu1qqU6ppiOiMBqoATAdiWoArDMhgZJ62IXLxHFRmTIQAH/R9PnfF/+WoNAygAD+8rQ2Z9GYffvXJ/F2Im6mE9iA3u3RJHOM8pwqOm3TXkrvsFLrgDBX7JEMdCQjsIfAM4AbxKZCvd00NFR6OunJkO6udabEBGboZhTCh2jcKjWSj0SXGSotv2e5fuzANAkXmIZCCh+jf6G3JI51Bd17v3lCgvhAAA==",
    downloadName: "ice-castle-queen-10.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-49-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 49.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-49.webp",
    blurDataURL: "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBgCdASoYACQAPu1qrE8ppiQiKrgMATAdiWUAyywLNuBvkbnNOFyKU34yWRaKIDyTgIZQQg7zhQAA/vQk7HPXI0zkIoswvzGMPAe+fhFfveH5TI97d2l9NCsIca5aiawvO/9IIDjUZUshe1tbtQWIEWmmkk/MsyujnM+lnhmmMwGB57jJvS4/0w2AAA==",
    downloadName: "ice-castle-queen-11.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-51-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 51.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-51.webp",
    blurDataURL: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwBQCdASoYACQAPu1wq1EppqOnKrgKATAdiWUAzFgKHfdR339lTOobOkaLB0KJsrxAAAD+28XZUI7hebuYMbxI6aVHcIknfWhmEKgtOVFIE6qE5EgyE1HX3UXQqekRnaET8AAA",
    downloadName: "ice-castle-queen-12.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-52-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 52.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-52.webp",
    blurDataURL: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQBACdASoYACQAPu1mrE8ppaQiJW5hMB2JaQAAHyWuiri8hCcg2UYlUhZx4bq4AAD+8OVFDyWMd1xf9nrWxkDuMHdZyF5gwwct9gsG8snnpnL9C8PrH3yvyBhziNYfG46mAAAA",
    downloadName: "ice-castle-queen-13.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-53-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 53.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-53.webp",
    blurDataURL: "data:image/webp;base64,UklGRggBAABXRUJQVlA4IPwAAADQBgCdASoYACQAPu1qqVCppaOiqrgMATAdiWcAv7HdhYqRbIT2znT9zts/cKhGA8h+rnakINq4hBgbTw0lX4AA/SZF3rI6nd1zXZGNstMRFdRhQQCb3U0YRtlz+m1u5y7Zmwtemq+9B3spC8D9AyxlFLak2Y9oCGDoaN7JFX7HHPPKQ3F8wkzOJVCFDtFho2C9xxEswkexv6PYdYOgpVbXzMpbMv8uZNd2a8wXUJsUG0BS+4GDMbOBXS0HE04PQlpeSfpCtQDXnCXxS1Do5DmkJHOIsIVRyB3NgiR2NgvlQnUW4QnT1JsnOIHiUayOzbQVA53KF7E/l18AAAA=",
    downloadName: "ice-castle-queen-14.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-54-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 54.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-54.webp",
    blurDataURL: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQBACdASoYACQAPuVkqE2pJiQiNVgIASAciWcAwNwguvsg6tXM7Gjbm6dAAP7xH6JNIvjhHFHEm1mb+dRBi8LjYaDkH58DyJ2nMiTaT3riOF4fQ3A7MAAA",
    downloadName: "ice-castle-queen-15.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-55-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 55.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-55.webp",
    blurDataURL: "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBQCdASoYACQAPu1oq0+ppiOiJW5hMB2JaQAAHdcstOwi3l/MLx5rb2qDyofw0dvDvIr8sEAA/YlW2zbN5IEPaaJhVm3xRwW9njObUo77NbvvsQYM7T+MEvCW18g2aS1jC+OGYjF0863I0OtrDCCTekT03UPhanMFkXLpek1rc/5/Wjh5blTe6b8EfA7C/WxHllQAAAA=",
    downloadName: "ice-castle-queen-16.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-56-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 56.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-56.webp",
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoYACQAPu1wq1MppiOipWsxMB2JaQDKtA9am30cWLLQAAD+8O30lcC6sir0BZl14pe6VRzx/K9o+RqFTyDrQpeAAAA=",
    downloadName: "ice-castle-queen-17.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-57-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 57.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-57.webp",
    blurDataURL: "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABwBQCdASoYACQAPu1iqE2ppaOiMBqqqTAdiWNdgFvXibuNdk9O1m2avMvpaPXQWw5gxb0AAP7zHrMe8F7YXOc++fOjwoPkM3GqH/OXmXEJPQ/8div8pF2RAfytvr/54zbGLnq3LFd/19Sh9BtcTnVAyw6L80XmGQsq004rwAAAAA==",
    downloadName: "ice-castle-queen-18.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-58-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 58.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-58.webp",
    blurDataURL: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQBQCdASoYACQAPu1kqlCppSOiqrgMATAdiWkAAB9J7pu6kog/Q9UhkpDzjOH90h6B4UAA/umM+fNbaEW/iPhFcDsT+D5yvkv4l/zzp8EtylBthK4P60vG9PStFE0PbZW194GHiWaA0/KY0okAAAAA",
    downloadName: "ice-castle-queen-19.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-60-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 60.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-60.webp",
    blurDataURL: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwBACdASoYACQAPt1YoE2opSMiNVv8ARAbiWMAAFvrtmGlWy8gHxPGZTnt8AN7cnAA/vV1DMC4K7iG3NeNsBnfcejg1U/X+U7jpx1r05J9L7jCH/qf9DXK4XgsI7nHY51vQWetNTvitwtd5dUQXZAA",
    downloadName: "ice-castle-queen-20.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-61-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 61.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-61.webp",
    blurDataURL: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQBACdASoYACQAPu1wrVIppqQiqrgIATAdiWMAABw54rYPOCmi+L50i9Bd9cYAAAD+9DLFNuML4wFWrmPq9GAY/3i8y3Lcdpsq8wbA+CYMB3d4vdyplGpWzxwcOUo9oAWin7DvbLft8YWdLxPMjvITBIccogAA",
    downloadName: "ice-castle-queen-21.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "ice-castle-queen-new-62-png",
    src: "/wallpapers/Horror Christmas wallpapers/new 62.png",
    thumbnailSrc: "/wallpapers/thumbnails/Horror Christmas wallpapers/new-62.webp",
    blurDataURL: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBQCdASoYACQAPu1apk2ppKMiNVgIATAdiWUAzNAWa1R3h6bRQXbLpaEBggFzbenAAP70IBDkZjlzgWV2oWI43XffzThF6PLIv/B8ZPfz/HDJI9tuJqFx7YvM/ivAW1qu0o74EG72AElGTIxiu31DUuPtOAAA",
    downloadName: "ice-castle-queen-22.png",
    alt: "AI-generated Horror Christmas wallpaper",
    themes: ["ice-castle-queen"],
  },
  {
    id: "cosmic-space-christmas-wallpapers-cosmic-christmas-01-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/:wallpapers:Cosmic Christmas 01.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cosmic Christmas wallpapers/wallpapers-cosmic-christmas-01.webp",
    blurDataURL: "data:image/webp;base64,UklGRmoBAABXRUJQVlA4IF4BAADQBwCdASoYADAAPu1qqFAppiOiqqoBMB2JZgCpJ1cWANguYerX0tMB23/dNmGEvj4jY+2F+oj4KjGzM1q+kol7GareCDjMgAD+t+u9Othl8ILaFsmHAiMFIBkk8RDazRJJU2NkUlvPKyflPU1trDIucN7SfwN/CHFwzujRT3Q3Kr1gW596UP2mP9kx58FlnsoPIcPO2CBpN4CEKBIW/rmYi4It8MjlErbodq2x/AF8cp+qioMqo7SBOOx+AGkJIEQNs3dlKF8g4deOfCqAa4PSFr7qPLYvhpsbRWdyWh1nO4/qWKRncykfFu/DGHk175AEfV3GppnvXoGpNLTrIzq4ss/eTz5VQTVyymAU+UpFLklG0oEXLcPrb8e0jWjhVaEoHe1Fau+ppupgWfbl6UaX0jOH8X7bB6EeHIlUUoIX7QdRkxg1c24Q7Mg10dvYfGQYtU+yJQdv7XX5d9AAAA==",
    downloadName: "cosmic-space-christmas-01.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-20251205-1521-futuristic-santa-sleigh-simple-compose-01kbpp2hk9em7tgat45jsh95r6-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/20251205_1521_Futuristic Santa Sleigh_simple_compose_01kbpp2hk9em7tgat45jsh95r6.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cosmic Christmas wallpapers/20251205-1521-futuristic-santa-sleigh-simple-compose-01kbpp2hk9em7tgat45jsh95r6.webp",
    blurDataURL: "data:image/webp;base64,UklGRgwBAABXRUJQVlA4IAABAADQBgCdASoYACQAPu1mqE8ppaOiKqwBMB2JbAC1G2MM58WCl5kd3/368dCihp2pIYqG63Fu/+TvHoLUAECAX2AA/ujdGO9lx+evD44LQ7ixY/b3RUY11S1+1H44v3bflWr5J+R1S7SbhPT9qUWJsVd8SfvEkwMstJosd9l3WeEmz2CrawX8j6aH8DLGfZlSSBZ0MoqgAs4hhJdgiZ1CAXrZG1omnZeKVHyzl+IsuW/FafXJMBbV6Z2zfeYADuxGKgcguQk4apxDr67SV0UXZSJkh74JQA8D5RieBiAkYTH3U4AeRLxH8RhhpeqS3qgljaiSyPniAWDw0f+ls5GAAAAA",
    downloadName: "cosmic-space-christmas-02.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-20251205-1525-glowing-orbs-in-snow-simple-compose-01kbppa7t0ezabafdg98zvc6hv-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/20251205_1525_Glowing Orbs in Snow_simple_compose_01kbppa7t0ezabafdg98zvc6hv.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cosmic Christmas wallpapers/20251205-1525-glowing-orbs-in-snow-simple-compose-01kbppa7t0ezabafdg98zvc6hv.webp",
    blurDataURL: "data:image/webp;base64,UklGRvYAAABXRUJQVlA4IOoAAACQBgCdASoYACQAPu1gp06ppSMiNVQIATAdiWYArDPsPKgNnxheX6DtgJIO9xerB52lQ2Z5zs8va4xxQaSgAP7Rov4KsWBXiA87h9E506Iqk6cejaZgc51pyr+PVnFLCt4AqfrnQJdfbbxJ/s808EyNnDxSkc8aWDKzvJXb0fFzLklvjC0FvaYQEWGbFOxGS1igG3POrKsU1HI0y6acZVbwsRr4Vp2xuYsGQu0aKcASBgXQkSnV0zjC6JjiIDCdwQZ53RzjaFQk7dtQ9uYjbtjJT2EkpWGFjKTCoKCjaAm3QBf971QAzMAAAAA=",
    downloadName: "cosmic-space-christmas-03.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-20251205-1528-candy-cane-ringworld-simple-compose-01kbpph0r8fkbrn2p6x960m1k8-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/20251205_1528_Candy Cane Ringworld_simple_compose_01kbpph0r8fkbrn2p6x960m1k8.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cosmic Christmas wallpapers/20251205-1528-candy-cane-ringworld-simple-compose-01kbpph0r8fkbrn2p6x960m1k8.webp",
    blurDataURL: "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAABwBQCdASoYACQAPu1iq04ppaQiKqwBMB2JagCdMoM4JAbMSJ/LFgFF1RNSHa+qVH8+2+/AAPtVXVmPrdwbiFG4/1lsHFdb00XdSydVGWmm4IyVy/QFpOpEv+pVT9qiTVBY3RKoCQylQvMMqHSjKsN8OcqDbdGDzFljV6ovI5kiIdSYELH8oys0qoIFBpSgl9/CJ1yeClxgkYMwqISNOq1ZnpEDt6msgiM+D/DIIE/v6GgVDAvZIymIOyP8+cXQdx9QAA==",
    downloadName: "cosmic-space-christmas-04.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-20251205-1540-celestial-angel-with-lantern-simple-compose-01kbpq5sngew1b7gdj74apayge-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/20251205_1540_Celestial Angel with Lantern_simple_compose_01kbpq5sngew1b7gdj74apayge.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cosmic Christmas wallpapers/20251205-1540-celestial-angel-with-lantern-simple-compose-01kbpq5sngew1b7gdj74apayge.webp",
    blurDataURL: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBgCdASoYACQAPu1erE2ppSSiMBqqqTAdiWMAzfwWeOx9IhZOCKgjfAUCV+uWFYpAPUVUL6/j3YiAAP7c1Gn4pAWm9QCA//yTMIBEQA+DmEhagojuJWj1zobnnRfkFbNF/3PodeOyQSuygJGdJzQfgE32306QgTkOsu9LAVCyBG3VnXNjhgTksysoAAAA",
    downloadName: "cosmic-space-christmas-05.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-new-19-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/new 19.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cosmic Christmas wallpapers/new-19.webp",
    blurDataURL: "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABwBQCdASoYACQAPu1or0+ppaSiJWzJMB2JZgCxH4oAnR0htx0w/JX1bu+Ca5rUEacBVPpAAPxPcLkh/AhMlq9I90PcHxdmxY+Rqo2sYSYAhW8YZNG7dhwhARkWYEx3AHsWDTEfV04KZYhGj3pV2x7N9VsGtcE+YNvQgJX8G2n4NEDbNu/5ux5w4/PHAJP//xsZCmcEI1ohgfyneAkegE2fAAA=",
    downloadName: "cosmic-space-christmas-06.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cosmic-space-christmas-out-0-40-png",
    src: "/wallpapers/Cosmic Christmas wallpapers/out-0 (40).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cosmic Christmas wallpapers/out-0-40.webp",
    blurDataURL: "data:image/webp;base64,UklGRhYBAABXRUJQVlA4IAoBAAAwBwCdASoYADAAPuleqk2pJSQiNVQMASAdCWYAsR9nK+x1UKWgdsOQHx0V3T5jjyUJpFmM551W0gcgx+YDzGPShuAA/vDewxWoRKO+bbZxf0VpyaQV2zGDjYNIuTY8slmH/+OmqjtuAREU/WorBu9AK68S8rhL7Re1r5txT22HUNjamUmuFw2z0s+A9ePL5AxJlk0tkxAD1b46PazLk3YcVN+tbYGemqvCw4q7Zkz9yiRaMKuT4iRDCgnNPic+IpzISEHX8+wc+yUg7Gtm6w+VNSoh2pokXQUr/VaMNURnLtlrJg8F9nbh2SoRZI99G+pMywesGF6f/+tM73mb9jThGy1Dwwn1fQAAAA==",
    downloadName: "cosmic-space-christmas-07.png",
    alt: "AI-generated Cosmic Christmas wallpaper",
    themes: ["cosmic-space-christmas"],
  },
  {
    id: "cute-christmas-robots-wallpapers-cute-robots-01-png",
    src: "/wallpapers/Cute Robots wallpapers/:wallpapers:Cute Robots 01.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cute Robots wallpapers/wallpapers-cute-robots-01.webp",
    blurDataURL: "data:image/webp;base64,UklGRvIBAABXRUJQVlA4IOYBAABQCACdASoYADAAPu1iqU2ppaOiMAgBMB2JbACAy3PCOdcBYnMbMrEIqaADoAZ0Rip6bggPxiKAIxqOB27LPOgiser8nKdFJJJUjwAA/uPx3gtjau0MTKRK9IOSr/FI51moFrCPK7W/0LHzTOeuAcZaRpd6mq4+NijJu8/j2P83jlpjdheejtJfTVS12f4KROa2U7EYJeN1f9PNfE25ThDbFtzUPte4YafSau2fjk7r84HrsVXWfvwnwy9mMh7R82lmLlkvBpMTSA2IlLmZFhNgr/8WIIts8OXuT1x6vd4/j7MYc4wRnZ+8eG2L+n7Mp+c6bppuhC0CKGAMhXKxbLquasDPq1ET5CXXmyzw2xOSUCBKkq34hsO/z/o4jd76/HXO6U1amiPtO9bRy5yufnu6wOQ6E/LbeeBvr5F46BGAq1369Xu+jpxEvGzPrG7ATkr4GsEFAPddjnNxYeJyWpva/wgMLTd2+TB+gKdNam/jeNhDb2fSDanP/W8O9tOn+a6g+8PQ7jmxiq/0TqNqmHlODEkIYVdYiDVVP8wbsTFiCUGGd8quC++5P40DQuFp43EziaYQio6aK6YZbMV6uRce3E81t+SdDfIVK3DsFtuVBn1UTQVfh7EmlzHVMFXD8i/Bq70AAAA=",
    downloadName: "cute-christmas-robots-01.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-1545-gingerbread-robot-delight-simple-compose-01kbpqfgcsf4n9npzvmaq635a3-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_1545_Gingerbread Robot Delight_simple_compose_01kbpqfgcsf4n9npzvmaq635a3.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cute Robots wallpapers/20251205-1545-gingerbread-robot-delight-simple-compose-01kbpqfgcsf4n9npzvmaq635a3.webp",
    blurDataURL: "data:image/webp;base64,UklGRuoAAABXRUJQVlA4IN4AAADQBQCdASoYACQAPu1kqk6ppaOiKqwBMB2JYgDE2AaKO2F4M96gPKdOj/kc6N/TPTYBHU2IEMKAAM1HRb4wu2dbeEKbQhy6zDZJKGPJrVHBNMEafZnrU+4r/m3ka/f56stRDx2PHxOyNdODXFHopFWQ5AlHPYXI5Xh8poEtP+Lbs38VtZAKn1Vvvn/Wa3JrBXSfNRbxOiBkJ5eqaBPdyu59hGIAJeUCCniMsigI9Y0c2hSlC45hqUg3osZHRjrWAu4466HomuZ+rwir9r2/zYgTZcp4NZgAGZDbOlSdAAA=",
    downloadName: "cute-christmas-robots-02.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-1559-festive-delivery-robot-simple-compose-01kbpr8gfeeb68v4fpj2mf4wf2-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_1559_Festive Delivery Robot_simple_compose_01kbpr8gfeeb68v4fpj2mf4wf2.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cute Robots wallpapers/20251205-1559-festive-delivery-robot-simple-compose-01kbpr8gfeeb68v4fpj2mf4wf2.webp",
    blurDataURL: "data:image/webp;base64,UklGRoABAABXRUJQVlA4IHQBAADQCACdASoYACQAPuleqU2pJSQiKq35IB0JbACdMoSERoGIzbzz/yjdA0lLSofLJIWIB5YKBIulNdJYwOGOClpjz9i6brqxKX1nVXQmxDIAAP7uiIJBTcv32USzliRXgF6louFgrXMcU4hiiwueqHPwLhYcPThUSKn7r8lp2RzouuiBZ0hbGmtKGjzTtQ3BuyxfaX2JTqOflDPA9PvRSeP9Df5W7YdegpEwL/Y/xXOOkIRNLCQ73HZfElJ6qxSj0k8VV0PvE3CQjXFVDuPRJT9dNLtJhxJUAfZom4AV9198jSgEE76ByAxowuE4x1YqjX6q2hT7P2ohpBmuOY2+oIYn6G1DZuQVH/P3sn9Zkh/5NHdloIAlaD/fIe8B9xAFASwGUqkVvOEYwdLOQwKWOBIvOF6+Lownnhw0lygC1OFf95sZ/4OGbqQW1nfa2gSazm/0zfKIKOP+oog0265NW/Y41Cev35xMB+2YJyhQ2FBcWICgAAA=",
    downloadName: "cute-christmas-robots-03.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-2007-dreamy-robotic-reindeer-simple-compose-01kbq6evw0f7er927xj14vy8bd-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_2007_Dreamy Robotic Reindeer_simple_compose_01kbq6evw0f7er927xj14vy8bd.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cute Robots wallpapers/20251205-2007-dreamy-robotic-reindeer-simple-compose-01kbq6evw0f7er927xj14vy8bd.webp",
    blurDataURL: "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAABQBQCdASoYACQAPu1urVIppiQipWsxMB2JYgC7AAV7AuvrKMQ+mN6ub5I5RsWxL+OHKAAA/ujSplvG/nBqcfI0yLg1gnWUqEUeya1VLm40jqp4gXia9qqg0i8a61hloCSBeReeKrrdBNz3bYRC1nf2E73avz77GJnoE+xBInYEEl4+GQlCTj9j3T0wfnYdJAnBFiXu37nXVnzfx3wx2FBLK3Uzeym6uoMie6+QG3fsi97DcpbMwRqx0w15PAAA",
    downloadName: "cute-christmas-robots-04.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-2016-robots-in-santa-s-workshop-simple-compose-01kbq6ymkjf4etd3edrgr3jkb1-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_2016_Robots in Santa's Workshop_simple_compose_01kbq6ymkjf4etd3edrgr3jkb1.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cute Robots wallpapers/20251205-2016-robots-in-santa-s-workshop-simple-compose-01kbq6ymkjf4etd3edrgr3jkb1.webp",
    blurDataURL: "data:image/webp;base64,UklGRvoAAABXRUJQVlA4IO4AAACwBgCdASoYACQAPu1orVEppaQiqrgKATAdiWgAnTlBPm42QKt+z/Kx93/Vav8HzrzzRyxYk4bFd76mv1VggAD+7D6M1MH0ule8++svZx1LxISIAQOVv06bOvxV4qnuRYhDoVZMHMWRsePSHk8NOPJTg+NCUfBscQA5EVTELqcOvRpRsFiUdE+7ELTvD5n0MNDu0ARWhKzDTaYJYAcuQMp0lKyykPjSNy2PtuJ5LbIlCbAt2PjurLN2zdGvLK6669hp5AGs5NjjNWBtXkdu5DCVjmNFgcsIJ9jKCet4H+XJzRpstadV6BKf/pi6ceAA",
    downloadName: "cute-christmas-robots-05.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-20251205-2021-futuristic-snowman-delight-simple-compose-01kbq77ah6fqcrd59cdmzg71n1-png",
    src: "/wallpapers/Cute Robots wallpapers/20251205_2021_Futuristic Snowman Delight_simple_compose_01kbq77ah6fqcrd59cdmzg71n1.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cute Robots wallpapers/20251205-2021-futuristic-snowman-delight-simple-compose-01kbq77ah6fqcrd59cdmzg71n1.webp",
    blurDataURL: "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAAAwBgCdASoYACQAPu1iqE4ppSOiNVQIATAdiWYArk+0iPBHRp3j0zL/SlRkt+X8oU6noNpo151C/iEAAP7DUEJlRX74lTQMbNdrNSLoZhc5AuNAqv8Qk2JU49LU3ymfY60Rsz0bWq+mhrCP4cOHZP27WHp8Qv3DBhj2pDQy7t8rleoDhXBXoQB3qt66ic1Vj9gyrX2rXPi9kzfSQeEwRLqD4AOTdaJeL/EH7b0yqvOvWV3NdFC0Ic1/CV/NlX5qptwrANsUuz6k9HJUQAA=",
    downloadName: "cute-christmas-robots-06.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-new-16-png",
    src: "/wallpapers/Cute Robots wallpapers/new 16.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cute Robots wallpapers/new-16.webp",
    blurDataURL: "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAADQBgCdASoYACQAPu1mqE2ppaOiKq35MB2JQBYj0GbzhXU/lvbwkMEygZVf0BsOh1FtBuvrABjXi+pNTdQ3E4AA/uX3ZOW018p/EO/rqsax4uqTAjCjWlImGHISiXPoLHfc9IOysBMNd6f8SEuBCb2ibvFLx+YuLVEloVJhkzmC6ocA86vuWDLxu+s46LiI0PAgfqdTvq/i+kC8dQgUkp+AjPoRLLKwUrko1e26LUXqFcxdPhmjvvsO7q7o5B0gjYxwHKJSC1jdYAhWmFIAAA==",
    downloadName: "cute-christmas-robots-07.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-new-31-png",
    src: "/wallpapers/Cute Robots wallpapers/new 31.png",
    thumbnailSrc: "/wallpapers/thumbnails/Cute Robots wallpapers/new-31.webp",
    blurDataURL: "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAAAQBgCdASoYACQAPu1mp08ppaMiKqwBMB2JYgCdM2v8ICQwbb8k5mBxymlQgLupFfw2Be3RmkYLJ4AA/lsKE9rNjfWNNop8+hicn47EeMFUA46GVaDt+C6GS+m3ZDJgDjAxNgVlvFMpnse/Z0u/pWp8VydCMblArjezxs5MsvkAsOFkSxRyGXX6tZ5UeNk7eVh9ScXnEQHnm5yWCsXNKnuQL6wzBcR9xAAVC+M9Q6yXNdZADCbKs30jUCRRtx1HKt0lJ3S5pHi2Cqzls6BMTq0uSSJEYWFoAbP9ZASThGZTzXEgv4DZwnw8Rg78RhIAAAA=",
    downloadName: "cute-christmas-robots-08.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "cute-christmas-robots-out-0-39-png",
    src: "/wallpapers/Cute Robots wallpapers/out-0 (39).png",
    thumbnailSrc: "/wallpapers/thumbnails/Cute Robots wallpapers/out-0-39.webp",
    blurDataURL: "data:image/webp;base64,UklGRp4BAABXRUJQVlA4IJIBAAAwCgCdASoYADAAPuFco02opSMiMA1REBwJbACdMscCv8S8Btq+ek0wDeXf9C/LTDW43uZYqW3qwovNyVvbUfSo+zs/SQfwY/APpzZ1rdgg6lbpCFmcSyq75wAA/uToyEtiwgggV7rVYpxjHHytePa9jW+gxS7WhSLli9p/cYxKmWjgHCzvP803305c/zesj3lX3i6hx9THj1xfYIPDjNW+4U2EbaENQ1oIjAWCRk52cSbtzhcPlN7jH4e162tHkeZo2op4DKQJ2v2R2nGcBrx/7Qo5hfPwX5bUfmmOnHRfb+RQQd42vtsDmjVy/ZRHdasCelIjqNIW6AhXG6qfBBRfSM1ouBMtgR8cxF0vc+Mw4pwoEQ1M5M7VivfxOlHFbx25v3aSGTsNCaEAzI0ecgEFCS+umL5e6sOXDGCu91ALgztCZ0JG1VLbv3yGsEbIH121ZSVbvkQdJjX3RqFu+rJP4FYbiiClZjNfgPDFXNIKUjLctPxooR16KynpSONrqO8VOZuBgA4p9jcUx8WM7mtYAAA=",
    downloadName: "cute-christmas-robots-09.png",
    alt: "AI-generated Cute Robots Christmas wallpaper",
    themes: ["cute-christmas-robots"],
  },
  {
    id: "pastel-candy-christmas-20251205-2027-cotton-candy-dreamland-simple-compose-01kbq7j43yf8y8a1np9z8ecc49-png",
    src: "/wallpapers/Pastel Candy wallpapers/20251205_2027_Cotton Candy Dreamland_simple_compose_01kbq7j43yf8y8a1np9z8ecc49.png",
    thumbnailSrc: "/wallpapers/thumbnails/Pastel Candy wallpapers/20251205-2027-cotton-candy-dreamland-simple-compose-01kbq7j43yf8y8a1np9z8ecc49.webp",
    blurDataURL: "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABwBgCdASoYACQAPu1qq1AppiOiqrgMATAdiWYAqS1BVAAISOSx9lqsY79gbPoFpiru3cQVoMxlWgeT+AAA/rXIpiKnuzC8Q01P5N37ZeGLCfsaenhMqKE8/Pi7HaWDgvWQ9jJEo8QJg4MG4YaQoCpDx2kyfY5OU5p9s0BcOoAYfLQ9JEdBwDAdiOzlkwDLoBCuBtfQU37bjU00+Sy8nRmKwAA=",
    downloadName: "pastel-candy-christmas-01.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-20251205-2032-pastel-candy-christmas-simple-compose-01kbq7w8gyfxkt23cyy2djb7hv-png",
    src: "/wallpapers/Pastel Candy wallpapers/20251205_2032_Pastel Candy Christmas_simple_compose_01kbq7w8gyfxkt23cyy2djb7hv.png",
    thumbnailSrc: "/wallpapers/thumbnails/Pastel Candy wallpapers/20251205-2032-pastel-candy-christmas-simple-compose-01kbq7w8gyfxkt23cyy2djb7hv.webp",
    blurDataURL: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBQCdASoYACQAPu1kqE2ppaOjNVQIATAdiWMAtRtCwRvEq/oWv14wzJNIq4ZqpcQYS3gA/rTVAMClpT9/Ih/MwE00h7XNHs0gdP5ZHvClZOujBFFiYmuDADern8PJnY8XZGubZV0eVDWNjiqvEaDE8tK4UAAA",
    downloadName: "pastel-candy-christmas-02.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-20251205-2035-lollipop-forest-enchantment-simple-compose-01kbq82esnejfrhph5xpadr1hw-png",
    src: "/wallpapers/Pastel Candy wallpapers/20251205_2035_Lollipop Forest Enchantment_simple_compose_01kbq82esnejfrhph5xpadr1hw.png",
    thumbnailSrc: "/wallpapers/thumbnails/Pastel Candy wallpapers/20251205-2035-lollipop-forest-enchantment-simple-compose-01kbq82esnejfrhph5xpadr1hw.webp",
    blurDataURL: "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAABQBgCdASoYACQAPu1mrVGppSQiqrgKATAdiWwAgYVPwB9xKsydfcQSZNoNQS3m+OCNRko4oFKLyuNEAADhDvPvZGcggAXu0MTf8j7ZyA/+bceH9Ypn94QR9h+XrDRX2raxjZqWVHdTXx5dIxUZyZq3ruJbMe/mYum15KyNzEfvMyXlM0Q2pWAE9oqd6FDNdgeTBosR7Id/fhKxpHE4zFiqWCA0/j2Amm2AH3CjPtk5PQusAAA=",
    downloadName: "pastel-candy-christmas-03.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-20251205-2127-candy-animal-winterland-simple-compose-01kbqb0494fw8btazcg3tk90sv-png",
    src: "/wallpapers/Pastel Candy wallpapers/20251205_2127_Candy Animal Winterland_simple_compose_01kbqb0494fw8btazcg3tk90sv.png",
    thumbnailSrc: "/wallpapers/thumbnails/Pastel Candy wallpapers/20251205-2127-candy-animal-winterland-simple-compose-01kbqb0494fw8btazcg3tk90sv.webp",
    blurDataURL: "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQBQCdASoYACQAPu1ur1GppiQipWsxMB2JQBfJBc2ZoDolmBD4y7cZHgA8XK416w3Fbah1g0YAAP7qitWQmS+9vh1UHSNCIxRYpmGDxFBd9ctU9MvUfMZqyPVrh4H9IvquQj+X2gM2fAn7iG8ar4DeOPgDTNbQBmTH6hWyGdPfjAGywAcVgC53JvvqGQwwNAtQQB2Jm3IvobhXZvfBBPKvZMEYEAAA",
    downloadName: "pastel-candy-christmas-04.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-out-0-29-png",
    src: "/wallpapers/Pastel Candy wallpapers/out-0 (29).png",
    thumbnailSrc: "/wallpapers/thumbnails/Pastel Candy wallpapers/out-0-29.webp",
    blurDataURL: "data:image/webp;base64,UklGRuABAABXRUJQVlA4INQBAABQCQCdASoYADAAPu1iqU2ppaOiMAgBMB2JZADK52c3qrJrCmgX+1yNKsW5Y4v1QfTRZLxTDGmjyQAPUD0UGaKX0y+r4NNuQRc5IzZGFn2VNZCIAAD+VNPRmsXwTx8uepvxxJ8TRCoxYLdQNTPGgn7NM4p/yQ9bx7x2JMzo0rNSVV2T6fsB0YRmY6P+m/ZLLXLLrZoKtlfpdw/rz9rHd2z2MoBZEr9vWbkUEmRAJWyDCpZutE7KrMGcBCsoyy6DeCJkUUABcVBwnzc95o4VqdYaSlIg9eXQzTiSDCJa/PlDxbvGEIxQhsFZuvZMw46N1TJ/Vt5YcVxse9q0ybaNB3FTI7v3cIIDdVOywgsUyz87zpdHgMY9+d9+OGPN/ecyk7fUqBFAvmNT5CeCBOYHpcMeTS+1nUcJaxLfCJABj1fSlCylfm7oTzxszFR6mOhCQO3cz6TGpD+yIG3DJwzqnEZZucAulsdwe6+98rw+KSt/aBTTFS6/uGGRd9c+stLrmks74AY9STA5ZrM8lQFD+H5Ntet3dEc5eVZdNwQJBnVquTOJH++Nxc4LfV1c7yUp3Ej0VSa285b6Fu/P+Nr4v6ov5JGn+shis9eonIVbIDuAxr8AAAA=",
    downloadName: "pastel-candy-christmas-05.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-out-0-30-png",
    src: "/wallpapers/Pastel Candy wallpapers/out-0 (30).png",
    thumbnailSrc: "/wallpapers/thumbnails/Pastel Candy wallpapers/out-0-30.webp",
    blurDataURL: "data:image/webp;base64,UklGRqQBAABXRUJQVlA4IJgBAABwCQCdASoYADAAPu1mpE4ppaMiMBqqqTAdiWQAyQeiaR3LCBuUCONSSa1trBJlVeJtIOga3RTbs6YvTyib9A363eY937MZgY3d9XqCUctJFfO34AAA/I2Fyf9bOH93JWN/Qiox9ZpXyS1nTE65XL7m7p4y/IWFB0spJU10Kso0PjOweOUBKz3rxGW2mdRAYFjgSWIbtsamr2sXP7tynU0JDLU1H4KkDgyTqC2qdXbhaWITN26jfB21AkcvZxknSGwmM4zjU4JfxoqLAT1HIe87xZKsGc+RhpPY9MuUCnLI4eRGCqnT9ff9Z1H58MCSMolZgJ20WlXav65IfW28+gOspt8+nnBH4TEDa0dMsZEUnf8EbOHtXsWIvM6F8vfW36Ws7vR5R5JBFgS3uyt5LnrCWc8Ky5DuWPDBaXYLyqJ5Jqr9QmJjXhWIP+68rBUFm7pmdLos5EHhaRjqrpmaBmx0qN5X5XdbDXjBsFvRSGX6Q7ntYplpkMZPui+7oDeAOFkSqeB80++Q48TUbHLGG9RD6Gv1YUmFIAA=",
    downloadName: "pastel-candy-christmas-06.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "pastel-candy-christmas-out-0-31-png",
    src: "/wallpapers/Pastel Candy wallpapers/out-0 (31).png",
    thumbnailSrc: "/wallpapers/thumbnails/Pastel Candy wallpapers/out-0-31.webp",
    blurDataURL: "data:image/webp;base64,UklGRvgBAABXRUJQVlA4IOwBAADwCACdASoYADAAPu1gqE2ppSOiMAgBMB2JZAC/a6XHotDhsWaC23jOrUZYGkCZuEidB5gDJP4wm8z6P6KReFeJcCJaUaqBnlzj0tdkirjZ+AD+VQMB/gDIH49vf2nwRhBLIKnDcvISxP9qtbmkHBYHh82PDbYXd/oZMnNOMkpW3b34lrKUtmOOuUlbD9Z+KuiBk6Pqq5jkDPRur7ryi7nB3n5FrkD3Qmdsepr0aVKD1+fs+tJvIy9VpUEtd2a4r7lzPppEe7En/7jXsl5VSOQwLqe5cYmfkNgvNsv1+vAFkAI4wtE1qRIY1lGA1DlVHlZGIyKglrPCK0pChlrR7WWv7+KmuWSF2K6rvhZ2EKn3Nh42cd/1ngnxoYh9PaRDS16jjLkU2/c80REvbFWDsFm++NWi8Ag3Aq8x+/a2kA0npJk4XSPYO/153GVvqNnEBts01ovOFmrGr0pCCbYoSkH8fG331kgtANMiOwtj5sbfO7I+xGRYBbiN2br+RWizhZ/24yjIu/qutgUYe8LIZQe1plzAz/KARlP6LCYlPQrPFBPcTA/1nKWb7X60/l5h4ZDSMmxluAi4qZ0WY58yqHeqs5+HM9LJzyL1b6dUEkV/lmpHtdlMVfeF1OPQkDDwfuBV+KfHJLq8sT4AAAA=",
    downloadName: "pastel-candy-christmas-07.png",
    alt: "AI-generated Pastel Candy Christmas wallpaper",
    themes: ["pastel-candy-christmas"],
  },
  {
    id: "snowy-forest-aesthetic-wallpapers-snow-aesthetic-01-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/:wallpapers:Snow Aesthetic 01.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/wallpapers-snow-aesthetic-01.webp",
    blurDataURL: "data:image/webp;base64,UklGRhYBAABXRUJQVlA4IAoBAABQBgCdASoYADAAPu1qrFCppaQiqqgBMB2JZgC7MwBJDag7G2ALaLmvIfZEc+j/U7YoV/F994MGX/G8IAD+9Zf747e3LjRDyF0XbBxefGEXHXwUel0dR0OHJUr+A6ZULmtpitFyv+vJJxiWQ7VLAlH0veCPW2braI7qlPXQOT6R/0M/6SSghYUDvGcQxiekoHybgtMAFpG6JEh6ukRgoGbUTaZ013ofdh+tDcNbc1ohXDqGBdZrEOp7ETLRWPU+HCPD6d3HN0E0CMQkCXIqs8Ib6vRp4szPbuISTPGZI8PoNj+Tn1Cxu7r/Uu2dJxoQUaseMdDLPSvq6yFqS99hVeAeHTdGKsKYAogAAA==",
    downloadName: "snowy-forest-aesthetic-01.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-wallpapers-snow-aesthetic-02-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/:wallpapers:Snow Aesthetic 02.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/wallpapers-snow-aesthetic-02.webp",
    blurDataURL: "data:image/webp;base64,UklGRiYBAABXRUJQVlA4IBoBAABwBwCdASoYADAAPu1gpk4ppSMiMBqqqTAdiUAWcIFQRxy9mJNBOFghHiQo+Pq7qE7FkWQcG3K3+BTLsLRErCQfpWBnAAD+2wfzdA9r+X4Pnr59ic0NULZU1kMx0m/+wlzqOhPLgkuDfRagd2bbYgpeOFZ9qEaKuQtUsYEv21PFs/pTwTwVlEhd62/dKs3SftuljhSxeVFKsUe6t0rnHTdjQsEo8A5Sj9+/Bg/7Fx3MOz69B0DagBn1da5+bKfW1BVsDgIJ/76/MG/WSbB6Tr+y6S6CuSdXuiUbn+lbAxkd3NpU4RmUXPLQWs3AcCzMD5OvKLtwb463ndsb9t50uxJ488DL5ZtTH3PCxGd/LWh4JIGJqPJIpivFIAA=",
    downloadName: "snowy-forest-aesthetic-02.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-20251205-2053-anime-empress-christmas-elegance-simple-compose-01kbq932cnfpxr8w3na7d510kw-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/20251205_2053_Anime Empress Christmas Elegance_simple_compose_01kbq932cnfpxr8w3na7d510kw.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/20251205-2053-anime-empress-christmas-elegance-simple-compose-01kbq932cnfpxr8w3na7d510kw.webp",
    blurDataURL: "data:image/webp;base64,UklGRkIBAABXRUJQVlA4IDYBAABQBwCdASoYACQAPu1krE+ppSQiKqoBMB2JagCo+Agdr8ZLr1DxtrzWQgBzKSncA+DjZcCTarg+yry2OIqbcdKcK6/0AMr3BsB4tPTHJGuyjGnKPpmu6hu8PMJkUqVlFj4iw0sqzR+EFnzlHbE8raDPW+aVlqMx97BNqOqqSe4P1ps4O+rMLzyldjKB243aCLIWhhYq3XmDTqwGEh0FuKKeTlUvy8n1swJ03Emn+UDHLqszgPAZE23wwnD/+9jBjMrPO2mMD4VsoJ5YabHU0aX5iuegO3Hkkt7FoluZ+uczmqRDgkU7wZgB5qr72BNsxSdcrz2SdOj/EWQEWezQv7Ttu/Rj4AibaBDfAOo7X6z02blSIoKZuJ/735nRhUGz2Sr24aNhSgo1OX8OAm0cWnlRK0AGAAAA",
    downloadName: "snowy-forest-aesthetic-03.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-20251206-1949-godzilla-s-cosmic-clash-simple-compose-01kbsqt2rdfnd8p3znmw59wn9x-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/20251206_1949_Godzilla's Cosmic Clash_simple_compose_01kbsqt2rdfnd8p3znmw59wn9x.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/20251206-1949-godzilla-s-cosmic-clash-simple-compose-01kbsqt2rdfnd8p3znmw59wn9x.webp",
    blurDataURL: "data:image/webp;base64,UklGRgIBAABXRUJQVlA4IPYAAAAwBwCdASoYACQAPu1eqE2ppKOiMBqqqTAdiWwAqSeSAfgwX1jLz93R1jDIeKMchZ4HKNswfHmgjhq+BLMzWS8c2UAA/ujSDgWGdxuf7Fub8neTeTSO4Vz0R7KxGDKCsg6X8wBB6QaSVubU0+xRsvye2mhpUwKiZVa3UMSnNIq03VpmZUaJ2qhQ/OH+bBqYbsnVs1ftesu16pkkN1UvS2YOxNhgVRodp7SATgK6Sss5fzi0+PEzptHrCnPkgLW/djToPoxFAqXhdSN0s9tvka/d/1F09skdN1AALs/k5ZEGakJ6xA8U83UExlLhGh6G5284dJ6AAAA=",
    downloadName: "snowy-forest-aesthetic-04.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-20251206-1953-epic-monster-clash-simple-compose-01kbsr235xf0ds535cnd6fajhw-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/20251206_1953_Epic Monster Clash_simple_compose_01kbsr235xf0ds535cnd6fajhw.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/20251206-1953-epic-monster-clash-simple-compose-01kbsr235xf0ds535cnd6fajhw.webp",
    blurDataURL: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JZgCdIExCu/5OqaqIrTPq2ZIQIAD+5gFVUI08NpvKZl/IVtLIZ0yglBP5Pk5W2d2yqLw3pxYDhbDaSd2LIwQq6dpoNRQXvQDV6l8j8STJZAv5ns55GVinXmRN4mAlxyHTZK3kMnxTflXE6OF+FEVYE13EBKcFb+uTsAAA",
    downloadName: "snowy-forest-aesthetic-05.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-12-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 12.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-12.webp",
    blurDataURL: "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOmUGQ6h2KJ/z/6gYwwBVprfAD+wUOi0BewiYX2IJKvckM8xapw1AHkBCH4ZQ+rcOmyfci2rbAh4cvZSa0wTyJvqBqjGEnWjXgypayQWtc4aYMIG1mANKUm81PevUjCA0FCgFUG9pcCUHEuN4TGjUiEk1wFG3jFcl8oLT7IAA==",
    downloadName: "snowy-forest-aesthetic-06.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-13-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 13.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-13.webp",
    blurDataURL: "data:image/webp;base64,UklGRkQBAABXRUJQVlA4IDgBAACQBwCdASoYADAAPu1yr1GppyQiqrgIATAdiUAUtbvFsV5Hczx1M1FHk3x3lzkw48252b/vwdxtWsf8s8sHryEA3mZ97DgA/vbJjYiq4atZZfWkd0JIVkmmgLAF0Gxx6GSPsVBE/r4ckBA+pt3l1i46oScHdUme4hKe4becj9urop426/KdXmBu88x7Ndu6bSIIKLu9wMQSZzMW3c01ae1I7YOunZdVyP5nWtr4bI+qoBsWtMji2/AtjxdMUlFrq+roI2d6aMF2JSBWlOMw54efPkHL7TBnBdzTe8RT2cWJwf27sXJ6Jh4dd6FkZSPS+rJqsI+QvC9kNgeYTA5YFLLRgWm+k2Ep9NSz5ah3WsxUtZ5ZBUsntN9ZsrIsleTOvT4TvqrPvGCpGcG2L5AW+t5YUKfREqUAAAA=",
    downloadName: "snowy-forest-aesthetic-07.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-18-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 18.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-18.webp",
    blurDataURL: "data:image/webp;base64,UklGRvQAAABXRUJQVlA4IOgAAACQBgCdASoYACQAPu1ur1GppiQipWsxMB2JYgCpJvn3UX9BOczC64GZU9IGEJ3P33vhhKbfUjdwjj5ZMhMAAP7xIN0PJ2bnimpbkn3tVrzJr530Mv7GEPAIdSkzAZ5/XFdkdBJlyCabXdCSVQZkLqqWOe6Ce8CzZyL6YqzVTIDjbHcrQxwqEZMEKaA/25HHyfN5d4CUSVXRsbcAINFYexJEHZP87uhVbYbMaE2KI4Eny+Oc+IBfH5PFE1zrpK5XY1Y7Hn6rfrbJVQMXChhJdqUNmEYzalQN5HLz55su8vCrOFzCQm+OkgAA",
    downloadName: "snowy-forest-aesthetic-08.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-33-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 33.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-33.webp",
    blurDataURL: "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAABwBgCdASoYACQAPu1crU2ppKSiMBqqqTAdiWwAnTL7OdgZIt1Nx/Gb+amAIy7VcgOCe2CgI11sXe1tqrAA/rnyi1gmqORiBwrRecvEPfM6ipJqNul1dnx4PISqkm9HNyl0VHwrBXgcdh57dFXMJ8Y8+8Smo7vE0Su7f5iyuieQhJUozPXdat7608rGMJZhB1UBJ7QMcWwsH+/l+3EtnDNOMA2/urp6EYdxeJuGCftFv2dYMnn8JT2ydvDPB9J4zdDx3e0puoVPPAAA",
    downloadName: "snowy-forest-aesthetic-09.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-34-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 34.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-34.webp",
    blurDataURL: "data:image/webp;base64,UklGRgIBAABXRUJQVlA4IPYAAAAwBwCdASoYACQAPu1qp08ppiMiKqwBMB2JbACpJ1C/ETI5PVP59UBB8LQAN12pawTsh5is45m67tT5dnyfgtDPdAgA/ujVeR3X7yPMOxd8yVHvoFSkQQxZZea+IaA3lIj6f6L6qQJESrokFMKcIzGcFqqlIemgV2Z/aU0ynb8V9cn+f6gb/M2t9FR2+k+y5zVrus23OrKk47OuwSdDrdOn2xu+xXX/52kVvzHlJFxnJeDcN12IVAObvsFkjR/xo0XC+lGq/1Qio3Y6pNGHLcO+tUt50mUkXfL3+7Rpe9VbPcyZhmCAPoVZGIG9kOm9q32ec9f0AAA=",
    downloadName: "snowy-forest-aesthetic-10.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-36-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 36.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-36.webp",
    blurDataURL: "data:image/webp;base64,UklGRggBAABXRUJQVlA4IPwAAACwBgCdASoYACQAPu1iqE2ppaOiMBqqqTAdiWwAsR77Qr+pgRi2okij7X/W0ByIuFbBTRr9S8xAuV0fQYW8RAD+2nOOGZV88D/AeeEZ22Xa1BUCqraSOcwSqtmmqqwT80TYtsYD0LmT8TzfYLt2rfrnF3VUy3SkniIidDzNZjakCpp5wnw8Y1/OWz0Tp7YXUgTu9FV+pUJ9K6NWATptFu34OvwJsbJQU3tzDC+gFbYBThijYMCvIxURNwOmRjaTOE38htyq4dnzfn0fy+2rjwEiE9FoOqMJgC8dqQZRUYTUtQn7qLOBZ03RMNcONHi/I7qPElIwIT6lVQFMAAA=",
    downloadName: "snowy-forest-aesthetic-11.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-41-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 41.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-41.webp",
    blurDataURL: "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAAAQBgCdASoYACQAPu1mqE6ppaOiKqwBMB2JQBYdgiegbI5gJIKxjz3RtegvzLl/SqsTvvB0mkt6sEAA/p4y74DQolk9bew/bDZHVlqIeVvzh3Z54yKFnJ7l15Q+9TuQJPAct33MoAKBGwi7/zdOQBvBsbLwIKhFWfFfHZIYBs8Z3QF6iLNI1rwv8pB35ASRGFEJnfy9nTmJ/Cw1H1nn/ZKThAaSLucVxUUrRYJAsqtMEYAA",
    downloadName: "snowy-forest-aesthetic-12.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-42-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 42.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-42.webp",
    blurDataURL: "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAABQBgCdASoYACQAPu1krU6ppaSiMBVaqTAdiWYArlWN1iAfaQigpsE6XTgZTyfwJG/kAt03p+n+1KOkAAD9K8aimugZOsRFUDoTRXt+rezoq8Y1hhcg9hzX9DS0RRcG9J+25FzQcHHAiueOt+Ly6GQR/K7Y/7syVtSehyRET29QFOAKtgms4MTYAkhK+vuZzR67l1VKx645dpmAMbqAokIV1ujQ1wyljaAm1OCA8XxGSCDhn6hhexpgqhZ5pa5mAAA=",
    downloadName: "snowy-forest-aesthetic-13.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-7-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 7.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-7.webp",
    blurDataURL: "data:image/webp;base64,UklGRigBAABXRUJQVlA4IBwBAAAwBwCdASoYADAAPu1sqlAppiOiqqoBMB2JQBWEKNh8sp5cz74B3wYIuD+annLUqiTiOKwf7hnzzBsKEFAI5adzloAA/sumsiZKLch3ONTcj/vXb/6fhBn78WzxJadWWZTc7L/m8HWhYDa1c7XRMNO8e0HVaAVyfkorZBQvrVVAqt9IuXYKVgUGPKw/4arYb6jRySLL8V+NgEQRSWGL2uLuLACl4J7BY53oCJhFNhETwJ4g8KcFEZw4Lat7Fx/n9cHRclwwmWd7G6AzdTUCyJmB2iCVtVXCLTeifSZHKSRPGUZpohaxth6SksQUBAOrpDh6Ip8Ty+fVwbUJXnm7dNZUrNOkbgh16TrvK+bS2/VLXRcaHdkuUymMUR8AAA==",
    downloadName: "snowy-forest-aesthetic-14.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-8-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 8.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-8.webp",
    blurDataURL: "data:image/webp;base64,UklGRo4BAABXRUJQVlA4IIIBAACQCACdASoYADAAPu1qqU6ppiOiMBqoATAdiUAVyeeN/hsLa4OgULeQiRvrIlW2JGLCPqV2JWwcBjzuL65vrZXSlBbeLCY9pb5OczgoAAD+zzOiWMRIpDrepPMfPEnpkv1/Y8xJPlmWmKacKPtVpEtITdOMVR2PL67CsI8Rvx2BGKwu4Y6+lCpahZG+0eIO5ScrWzt845O9KK/R3fh6EsbAof6zac3R7QwgyqnUqOdk2qUPuAt2MZLK3bvQVCC9ZXbrPSr5MhHJ0WAjSS4zrlNwrwsDqoaJ1AgQw6hlgKs+tc+reI1Zj6g2Gu+7vevVARzyokzU356ad1en/rjuW73X2Rr2DchFGrH7AUKplbfc/5THvBitc5fyMzGa/2KR7BAxa2Wo/i28NFtRDoYKBcm2lnKPBFBmQVvwkyM0DQCsbU3vP0jVV0WLG5LPddgYOwRVdITzeqMay0d1adYXvGGyNyZ2CDuDzbkYgrqg8+42JtLr5nk+rag6WChouMiKhvdAAA==",
    downloadName: "snowy-forest-aesthetic-15.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-new-9-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/new 9.png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/new-9.webp",
    blurDataURL: "data:image/webp;base64,UklGRoQBAABXRUJQVlA4IHgBAADQBwCdASoYADAAPu1iq08ppSOiMBqoATAdiWoAqScTBEhZPii45UHI8QTIluKXBOyPqso4M/A+EIYkIL9Uu/MW6m+mFy+mUAD+ugKEd9Yl5o1vcsU8h4t9YrS7K2pf3npalywh79VqKq7EMN5rX8lWXZSZZ8ChmryBSrAXqWQovi6j4EeyMDl7K5p2OBt9KhSzHrcx7FYvNLfEe5jAvwvbWNoA1mnjpLSv2Bj3oAfT6xo+JWZ7GBQeUsBRx4Q5yiv7IW4vZbp4QIpdQS/c+MPXuVQEy312XJr7Gixhbwy6WB9hEbUdX3R4oXHZK4X4uHvI4fnJihzSDHGCozxnV47bxWIKMb4jkqzJAfw5rOx5xfV1gCzype0Gc4k1pLjMEnsBJAzuA042OSf4GwywayPwf7VoeLllTUQwBSQxEsvC/zLfhHprZ3xT6Te2+b3T+FY3MuYX38LMfrXgJ5n4Q3XdRJXYGzdOYM08hOsSaswMMoLIr+2VAAAA",
    downloadName: "snowy-forest-aesthetic-16.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-10-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (10).png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/out-0-10.webp",
    blurDataURL: "data:image/webp;base64,UklGRmQBAABXRUJQVlA4IFgBAADwBwCdASoYADAAPu1kqE8ppSOiKqwBMB2JYgCvLVMJ/qaUU3uGVUCjf5bFCNEKeJntpDF8zpZi87riiXPRsTqlxE4vE5uPeAAA/ujv0zUXTzoeaFMcEqua2CiLa0zGLe4A4bvQ1qAzx87iYSYzyUNAB0fQJvrwOxXArIqWICFeBRuwUZdM+yRYbwtj9eC62+uhxMJfoGQgKuUOY5ROl0Q5Yy5TUD+yyigCest4n3DC2U+atZO3KoAtiSU47eXkseyS48HQ/YJw19EF0BHWFQkyrg3JYnnvz4Eg+qccwH+s66600um4We5JuUgKzhlE2WrmQ/CJ+SCc4jg13Cw2jsmokkZjE9qoHIKQokShSa7eZdNJkhG6rEFMfq9IrlO6V6gOtoZ4fhd+3wC9ADFPMF0mNVyRFj8PNtL6Hh2uOIBmB3GC0iIlLPIP8mXO3hqbgRdfFUytJQ4AAA==",
    downloadName: "snowy-forest-aesthetic-17.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-16-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (16).png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/out-0-16.webp",
    blurDataURL: "data:image/webp;base64,UklGRtIBAABXRUJQVlA4IMYBAACwCACdASoYADAAPu1sqk6ppqOiMBqoATAdiUAWHl5Gto6WXCyytJMzwHHdCgA1RnTRcUigSO+lJzW4HlvzfBzUfz7J5MbWTnVidkbY5oAA/uv/FuFj5vsmx/u6V68TKBmJnm71i3Awv2rIsIPZ5NNLxw0TWISh5sObNqyAptpwvDV5CCA5/F6Ehx9pV4vZr2DdInc1eXEl+y9LNPhuIX9OxqjaX99ewSPh30EuWcCv+NYqHzXK0+cRL6C+tRhXt7oJcK8tsPy7sXoHJwxAB8bzDTPPuotXPmyarA/yXoaA97qT6FDWh/JeP5JOsx6zYO4b2WRHqV4jQXqHVtrRxCqL46rdRlJVrSeWOO0MKaAa7wJ1AOCRyu84Btjx/we1TanhPpr2uprtzQl/c8qi3OD9A2p/E51IL4UaclKATQLreXwLoUT50d5jTPfc2zSrj44USnGsKwH2ksAPh8IhFvvXO4pPz/qasxDnGcaIvIaAnBN5pnrPgOGJAYD4l89NmUjEFXc3MtEutkOBjF0BDJrgaCf3Ur+JhBQjyaoMRCp79Gpd3dhG/r8UBMuPv5FaHdOcsTS6nsU6vtJQQgGacEnWw2wkRIgA",
    downloadName: "snowy-forest-aesthetic-18.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-27-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (27).png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/out-0-27.webp",
    blurDataURL: "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAABQBwCdASoYADAAPu1irU+ppSQiKrgMATAdiWIAsR64xyAkB5DzdseZUDaj1U7eXXSzZm9xpPMwIMDhn/qDIoNc/1FAAP7yqCGU/ZX1ivUZx8hcyfE/GV7P1X3vnIRvduP9HrIgIFhUoHCAADNVGQZA6PrBXO7yJHMrGHTvQj70fzL+WgvabRDRSOVbm5uloiWA8KjzEycyJSMDjh7rWKkZF/u9eef4bXpMMZO+58Z/SgvJsOHoDLm1wZEALjDna9YDIuv/vNEhHsMYAiBwG8xtmlzKZrzVgAA=",
    downloadName: "snowy-forest-aesthetic-19.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-32-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (32).png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/out-0-32.webp",
    blurDataURL: "data:image/webp;base64,UklGRhoBAABXRUJQVlA4IA4BAAAQBwCdASoYADAAPulYqE2pJKQiMBqtUSAdCUAW/XLYaelDmhBjZi2DOCPf54dKniunO3ZI9xO2ulUkMZpJfh5VzAD+8zPUc8LE2u4NQ3uytzelwY32bTvxpCKOWdqA7fvIbO4xrVjsdXDsG7cZDUQp7hzAte6hE0Mbs/gVgi/3Fqy1RQFsOFC0XICdsmcyD5CXgtlxL6qEiALJZbFA7Bw7a0Nijt1vkpBqauG40WJIFgesX5Ycz2SkhHbF4oC5ZOKCD/m+RybVnwglg9ZNe5D4yBQBVoVEGAF+uwHd5ZxLXKg/EkLARl17h0mPIdR7qzz4ETy70ObUZqLXCnncJsQ/DiWUkmXLmbDeDN+mgAA=",
    downloadName: "snowy-forest-aesthetic-20.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-33-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (33).png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/out-0-33.webp",
    blurDataURL: "data:image/webp;base64,UklGRjIBAABXRUJQVlA4ICYBAADQBgCdASoYADAAPu1oqU6ppiOiKqwBMB2JaAC7Mv63pNbo+5uwWiLBIOAOQRHYz2+fY1q0qcEs/ZjaizB2LgAA/vLVpRXmzW2NPNwXU0dhIlX52DMg0zhvj/5two7D5TUuLwuaf4ULpF7T6GoPhu4b3KKOv6uCBqRd2xwk5OlMGbv3clXxdlLq9I8T79A/ZffpqQrqoncHjLckOsjOWxVswzqiNbKxF9z2rmZhSc3QUYidDbMVxu/C1I1gJI5gG2NmZMRvEW/Noxlg/jDkxEV8YXS0dOVio4igWCgIIG3IYKE6lKzcXD6T3alx7j8Ho4Tp7m5fXcPNWUbkTWiqz6Q9FCaPQ1WKAEAIvuadyIoUshbTBML10LDxzFjblFXkomweDmx7AAA=",
    downloadName: "snowy-forest-aesthetic-21.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-42-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (42).png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/out-0-42.webp",
    blurDataURL: "data:image/webp;base64,UklGRvoAAABXRUJQVlA4IO4AAAAwBwCdASoYADAAPu1kqU2ppaQiMAgBMB2JQBajbq9BGwRB8rzFskUxaxrAH9Wl7ylNLK0uW5wd/KgCO9sa38X7YOgA/j22M/n1VPqjHXdsZctKg7biQ4uXgtwnbvHFKXg5cYTYPUMesI/yvaDlU5f4Sb4THEcpu6Ws0K8FRrqR287tz+5lBwtgDSRjBghgxkLClwJXDWbKDfRqOqpaNoLuZXL1E05LXimuKs/Hsh9rz2kvULNfJFSCWFBGdI3q4j0NtrA5qkoYFjvnf0YCJkzL+uG7jKFMCaIMj/SxQ/gSCEybiN0tvKoWJigOMoAA",
    downloadName: "snowy-forest-aesthetic-22.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-43-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (43).png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/out-0-43.webp",
    blurDataURL: "data:image/webp;base64,UklGRmIBAABXRUJQVlA4IFYBAAAQCACdASoYADAAPu1orlEppaQiqrgKATAdiWgAtRtjxx/E8/nGx4nmEc4j8ZbXgMEV9ctBW78RiZ4lXtoOaR6bQtpX5Kw0womwAP7jSlD+RCDKO7I/zpVHJQYVfeVnLsljtmEkMtDWMsSS+rQip+JaI7o/T/vI9Bmqes/B5y74zj17o3isQNlYmCLcb+j6DTS2LYKM1zegJT2N9L3YBGT/a8u7ScruXI+ZKnpNlZvfHODJPT2PF4KizbpwJci+32LyjxYGyXq+jqvS78ZyYznvP6slNVOdrZuTaiJXZ5ztKXzzgKF/u+UQCp4CCb1Qce9E5C+rbnqRRexYbE8k+y5n3hTaHJhWniPs4H6uHATLtgjrdvvB7tcPtNsgYTCp/hvqWTvUZ6aVBIq5gfsi+4lNTN+zzd1H5+zJUXwIJF78ankBcb08HbVg6gCMl5wzCbHaKEYAAAA=",
    downloadName: "snowy-forest-aesthetic-23.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  },
  {
    id: "snowy-forest-aesthetic-out-0-9-png",
    src: "/wallpapers/Snow Aesthetic wallpapers/out-0 (9).png",
    thumbnailSrc: "/wallpapers/thumbnails/Snow Aesthetic wallpapers/out-0-9.webp",
    blurDataURL: "data:image/webp;base64,UklGRgoCAABXRUJQVlA4IP4BAACQCgCdASoYADAAPu1gqE2ppSOiMAgBMB2JZgCdMzPQEkNef1nLfA0zPedZ8dy/hJFAjnxxkqYbrjKdWEZzsbXxYq2z08Xcco46Gg6m9MjLLDPS2YfDIfyCgZ3vBXAA/uxXgFDnVL76q3rCu4zJyQu9hvcY2Gqd1WIuFuw9rpVDWV2CR3Fxd+uDe5XNC+NgFff8Qvg4fHRgFXjTrTiR/XBA1Tejuf6QfcgibjmHUbttndN/bRXSYKny5iJVxbaHeib0ziirtBxs4Gfr5azJyeVGhR4n3Th0J3CqJrdhJ2849h5x71SZ7+DTJ7bTj8KnjgJvHs9xDGyfRcz5DEaogzPH0rERoPI0O848jea3nm7Hxl02T46kDb9bjteujBWfNS8Pms25H8focPaHIVbsFYnrW2/Q6VSCLvtBEtpA8LyGUmhVyk0d4jDjmjsIoN0QNORR/KjMZso9bPY+ROeKUOMvANCrkl9Dv4Uc4vAsBqEezh7ZVTXXOWMdOTSUk5vFIigzXV0qkriFtHWwON7wWQogu8BYraVWJCWYPO1TEPbWBv21u9dTe4J2E4Qz7HKm9Q6CfLN1UtiAip9Z2ihvBA6EmBqD42KJJomPqkZ6mMZXPYvhtd7AoppZXWXjc3NFjYSwYNGW/7DmQAB7UrQ5qZc/Uhr38hjFnK8VtdJ1kAA=",
    downloadName: "snowy-forest-aesthetic-24.png",
    alt: "AI-generated Snow Aesthetic Christmas wallpaper",
    themes: ["snowy-forest-aesthetic"],
  }
]
